export interface Quote {
    text: string;
    author: string;
}

export const quotes: Quote[] = [
    { text: "인생은 폭풍우가 지나가기를 기다리는 것이 아니라, 빗속에서 춤추는 법을 배우는 것이다.", author: "비비안 그린" },
    { text: "나를 죽이지 못하는 고통은 나를 더 강하게 만든다.", author: "프리드리히 니체" },
    { text: "너 자신의 무지를 절대 과소평가하지 마라.", author: "알베르트 아인슈타인" },
    { text: "가장 위대한 영광은 한 번도 실패하지 않음이 아니라, 실패할 때마다 다시 일어서는 데 있다.", author: "공자" },
    { text: "남을 아는 자는 지혜롭고, 자기를 아는 자는 명철하다.", author: "노자" },
    { text: "어디를 가든지 마음을 다해 가라.", author: "공자" },
    { text: "자신을 사랑하는 법을 아는 것이 가장 위대한 사랑이다.", author: "마이클 휘트니" },
    { text: "행복은 이미 만들어진 것이 아니다. 당신의 행동에서 비롯된다.", author: "달라이 라마" },
    { text: "어두움을 저주하는 것보다는 촛불 하나를 켜는 것이 낫다.", author: "공자" },
    { text: "우리가 하는 일은 바다에 붓는 물 한 방울에 불과하지만, 그 한 방울이 없다면 바다는 그만큼 줄어들 것이다.", author: "마더 테레사" },
    { text: "변화는 필연적이다. 성장은 선택이다.", author: "존 맥스웰" },
    { text: "상처받은 치유자만이 진정으로 치유할 수 있다.", author: "칼 융" },
    { text: "너의 시야는 너의 마음을 들여다볼 때만 맑아질 것이다. 밖을 보는 자는 꿈을 꾸고, 안을 보는 자는 깨어난다.", author: "칼 융" },
    { text: "인생은 자전거를 타는 것과 같다. 균형을 잡으려면 계속 움직여야 한다.", author: "알베르트 아인슈타인" },
    { text: "중요한 것은 멈추지 않고 질문하는 것이다.", author: "알베르트 아인슈타인" },
    { text: "내일의 꽃은 오늘의 씨앗 속에 있다.", author: "속담" },
    { text: "조용한 마음이 묻는다. 걱정해서 해결될 일인가? 아니라면 왜 걱정하는가.", author: "티베트 속담" },
    { text: "진정한 발견은 새로운 땅을 찾는 것이 아니라 새로운 눈을 갖는 것이다.", author: "마르셀 프루스트" },
    { text: "너무 소심하고 까다롭게 자신의 행동을 고민하지 말라. 인생은 실험이다.", author: "랄프 왈도 에머슨" },
    { text: "그대가 오랫동안 심연을 들여다보면 심연 또한 그대를 들여다본다.", author: "프리드리히 니체" },
    { text: "삶이 있는 한 희망은 있다.", author: "키케로" },
    { text: "산다는 것은 숨쉬는 것이 아니라 행동하는 것이다.", author: "루소" },
    { text: "언제나 현재에 집중할 수 있다면 행복할 것이다.", author: "파울로 코엘료" },
    { text: "신은 용기 있는 자를 결코 버리지 않는다.", author: "켄러" },
    { text: "피할 수 없으면 즐겨라.", author: "로버트 엘리엇" },
    { text: "단순하게 살아라. 현대인은 쓸데없는 절차와 일 때문에 얼마나 복잡한 삶을 살아가는가?", author: "이드리스 샤흐" },
    { text: "먼저 자신을 비웃어라. 다른 사람이 당신을 비웃기 전에.", author: "엘사 맥스웰" },
    { text: "먼저핀 꽃은 먼저 진다 남보다 먼저 공을 세우려고 조급히 서둘지 마라.", author: "채근담" },
    { text: "행복한 삶을 살기 위해 필요한 것은 거의 없다.", author: "마르쿠스 아우렐리우스" },
    { text: "절대 포기하지 마라. 당신이 되고 싶은 무언가가 있다면, 그에 대해 자부심을 가져라.", author: "엠마 톰슨" },
    { text: "계단을 밟아야 계단 위에 올라설수 있다.", author: "터키속담" },
    { text: "오랫동안 꿈을 그리는 사람은 마침내 그 꿈을 닮아 간다.", author: "앙드레 말로" },
    { text: "좋은 성과를 얻으려면 한 걸음 한 걸음이 힘차고 충실하지 않으면 안 된다.", author: "단테" },
    { text: "행복은 습관이다, 그것을 몸에 지니라.", author: "허버드" },
    { text: "자신감 있는 표정을 지으면 자신감이 생긴다.", author: "찰스다윈" },
    { text: "평생 살 것처럼 꿈을 꾸고, 내일 죽을 것처럼 오늘을 살아라.", author: "제임스 딘" },
    { text: "성공의 비결은 단 한 가지, 잘할 수 있는 일에 광적으로 집중하는 것이다.", author: "톰 모나건" },
    { text: "꿈을 계속 간직하고 있으면 반드시 실현할 때가 온다.", author: "괴테" },
    { text: "문제는 목적지에 얼마나 빨리 가느냐가 아니라 그 목적지가 어디냐는 것이다.", author: "도서 '인생' 중" },
    { text: "겨울이 오면 봄이 멀지 않으리.", author: "셸리" },
    { text: "인생이란 학교에는 불행 이라는 훌륭한 스승이 있다.", author: "프리체" },
    { text: "알면서 행하지 않는 것은 모르는 것과 다름없다.", author: "왕양명" },
    { text: "길을 잃는다는 것은 곧 길을 알게 된다는 것이다.", author: "동아프리카속담" },
    { text: "기회는 새와 같은 것, 날아가기 전에 잡아라.", author: "스마일즈" },
    { text: "타인을 돕는 것이야말로 진정한 삶의 예술이다.", author: "빈센트 반 고흐" },
    { text: "행복의 한 쪽 문이 닫히면 다른 쪽 문이 열린다. 그러나 흔히 우리는 닫혀진 문을 오랫동안 보기 때문에 우리를 위해 열려 있는 문을 보지 못한다.", author: "헬렌 켈러" },
    { text: "해야 할 것을 하라. 모든 것은 타인의 행복을 위해서, 동시에 특히 나의 행복을 위해서이다.", author: "톨스토이" },
    { text: "작은 기회로부터 종종 위대한 업적이 시작된다.", author: "데모스테네스" },
    { text: "최고에 도달하려면 최저에서 시작하라.", author: "P.시루스" },
    { text: "삶을 사는 데는 단 두 가지 방법이 있다. 하나는 기적이 전혀 없다고 믿는 것이고, 또 다른 하나는 모든 것이 기적이라고 믿는 것이다.", author: "알베르트 아인슈타인" },
    { text: "당신이 할 수 있다고 믿든 할 수 없다고 믿든, 믿는 대로 될 것이다.", author: "헨리 포드" },
    { text: "세상은 고통으로 가득하지만, 그것을 극복하는 사람들로도 가득하다.", author: "헬렌 켈러" },
    { text: "도전은 인생을 흥미롭게 만들며, 도전의 극복이 인생을 의미 있게 한다.", author: "조슈아 J. 마린" },
    { text: "위대한 이들은 목적을 갖고, 그 외의 사람들은 소원을 갖는다.", author: "워싱턴 어빙" },
    { text: "당신의 인생은 당신이 하루종일 무슨 생각을 하는지에 달려있다.", author: "랄프 왈도 에머슨" },
    { text: "성공은 매일 반복되는 작은 노력들의 합이다.", author: "로버트 콜리어" },
    { text: "시작이 반이다.", author: "아리스토텔레스" },
    { text: "실패는 성공을 위한 리허설이다.", author: "어니 J. 젤린스키" },
    { text: "나만이 내 인생을 바꿀 수 있다. 아무도 날 대신해 해줄 수 없다.", author: "캐롤 버넷" },
    { text: "웃음 없는 하루는 낭비한 하루다.", author: "찰리 채플린" },
    { text: "스스로를 존경하면 다른 사람도 당신을 존경할 것이다.", author: "공자" },
    { text: "무례한 사람의 행위는 내 행위가 아니니 내 버려두라.", author: "법정 스님" },
    { text: "가장 큰 위험은 위험 없는 삶이다.", author: "스티븐 코비" },
    { text: "시간은 인간이 쓸 수 있는 가장 값진 것이다.", author: "테오프라스토스" },
    { text: "당신이 있는 곳에서, 당신이 가진 것으로, 당신이 할 수 있는 것을 하라.", author: "테디 루즈벨트" },
    { text: "행복은 목적지가 아니라 여정이다.", author: "소크라테스" },
    { text: "다른 사람의 삶을 사느라 시간을 낭비하지 마라.", author: "스티브 잡스" },
    { text: "인내심을 가져라. 모든 것은 쉬워지기 전에는 어렵다.", author: "사디" },
    { text: "침묵은 때로 가장 강력한 외침이다.", author: "영화 '인생은 아름다워'" },
    { text: "나무를 심기에 가장 좋은 때는 20년 전이었다. 두 번째로 좋은 때는 바로 지금이다.", author: "중국 속담" },
    { text: "바람이 불지 않으면 노를 저어라.", author: "윈스턴 처칠" },
    { text: "인생에서 가장 큰 후회는 하지 않은 일들에 대한 것이다.", author: "마크 트웨인" },
    { text: "미래는 꿈의 아름다움을 믿는 자들의 것이다.", author: "엘리너 루즈벨트" },
    { text: "성공이란 열정을 잃지 않고 실패에서 실패로 거듭 나아가는 능력이다.", author: "윈스턴 처칠" },
    { text: "한계는 당신의 마음 속에만 존재한다.", author: "익명" },
    { text: "오늘 걷지 않으면 내일은 뛰어야 한다.", author: "카를레스 푸욜" },
    { text: "가장 어두운 밤이 가장 밝은 별을 만든다.", author: "도스토예프스키" },
    { text: "사람은 오로지 가슴으로만 올바르게 볼 수 있다. 본질적인 것은 눈에 보이지 않는다.", author: "생텍쥐페리" },
    { text: "모든 위대한 진리는 처음에는 신성모독으로 시작된다.", author: "조지 버나드 쇼" },
    { text: "사랑은 우리가 가진 유일한, 시간과 공간을 초월하는 것이다.", author: "영화 '인터스텔라'" },
    { text: "지금 잠을 자면 꿈을 꾸지만, 지금 공부하면 꿈을 이룬다.", author: "훈계" },
    { text: "독서가 정신에 미치는 영향은 운동이 신체에 미치는 영향과 같다.", author: "리처드 스틸" },
    { text: "모든 성취의 시작점은 갈망이다.", author: "나폴레온 힐" },
    { text: "천재는 1%의 영감과 99%의 땀으로 이루어진다.", author: "에디슨" },
    { text: "희망은 깨어있는 꿈이다.", author: "아리스토텔레스" },
    { text: "너 자신이 되어라. 다른 사람은 이미 모두 누군가가 차지했다.", author: "오스카 와일드" },
    { text: "삶이란 우리의 인생관이 만들어내는 것이다.", author: "마르쿠스 아우렐리우스" },
    { text: "우리는 우리가 반복적으로 하는 행동의 결과물이다.", author: "아리스토텔레스" },
    { text: "불가능은 소심한 자들의 환상이다.", author: "나폴레옹" },
    { text: "두려움은 희망 없이 있을 수 없고, 희망은 두려움 없이 있을 수 없다.", author: "바뤼흐 스피노자" },
    { text: "지혜는 경험의 딸이다.", author: "레오나르도 다빈치" },
    { text: "교육은 세상을 바꿀 수 있는 가장 강력한 무기다.", author: "넬슨 만델라" },
    { text: "친절은 언어장애인도 말할 수 있고 청각장애인도 들을 수 있는 언어다.", author: "마크 트웨인" },
    { text: "사랑받고 싶다면 사랑하라, 그리고 사랑스럽게 행동하라.", author: "벤자민 프랭클린" },
    { text: "평화는 미소에서 시작된다.", author: "마더 테레사" },
    { text: "진실은 결코 속이지 않는다.", author: "칸트" },
    { text: "지식이 없는 성실은 약하고 소용없으며, 성실이 없는 지식은 위험하고 두렵다.", author: "사무엘 존슨" },
    { text: "행동은 모든 성공의 기본 열쇠이다.", author: "파블로 피카소" },
    { text: "준비하지 않은 자는 기회가 와도 소용없다.", author: "알렉시스 드 토크빌" },
    { text: "기적은 대개 부지런한 노력에 대한 보답이다.", author: "그레이" },
    { text: "겸손은 사람을 머물게 하고, 칭찬은 사람을 가깝게 하고, 넓음은 사람을 따르게 하고, 깊음은 사람을 감동케 한다.", author: "다산 정약용" },
    { text: "말은 마음의 초상이다.", author: "존 레이" },
    { text: "음악은 영혼의 산물이다.", author: "베토벤" },
    { text: "예술은 거짓을 통해 진실을 말한다.", author: "파블로 피카소" },
    { text: "자유는 책임이다. 그래서 대부분의 사람들은 자유를 두려워한다.", author: "조지 버나드 쇼" },
    { text: "용기란 두려움이 없는 것이 아니라, 두려움보다 더 중요한 무언가가 있다는 판단이다.", author: "앰브로스 레드문" },
    { text: "성공한 사람이 되려 하기보다는 가치 있는 사람이 되려 하라.", author: "알베르트 아인슈타인" },
    { text: "꿈을 이루기에 너무 늦은 나이란 없다.", author: "조지 엘리엇" },
    { text: "인생은 과감한 모험이거나 아니면 아무것도 아니다.", author: "헬렌 켈러" },
    { text: "나만이 내 운명의 주인이요, 나만이 내 영혼의 선장이다.", author: "윌리엄 어니스트 헨리" },
    { text: "당신이 세상을 바꿀 수 있다고 생각할 만큼 미친 사람들이 결국 세상을 바꾼다.", author: "로브 실타넨" },
    { text: "어제의 나보다 더 나은 오늘의 내가 되어라.", author: "힌두 속담" },
    { text: "세상의 소금과 빛이 되어라.", author: "성경" },
    { text: "사랑은 모든 것을 이긴다.", author: "버질" },
    { text: "진정한 친구는 세상이 다 떠날 때 들어오는 사람이다.", author: "월터 윈첼" },
    { text: "행복은 나누면 배가 된다.", author: "스웨덴 속담" },
    { text: "감사는 고결한 영혼의 얼굴이다.", author: "T. 제퍼슨" },
    { text: "용서는 복수보다 낫다.", author: "피타쿠스" },
    { text: "인내는 쓰지만 그 열매는 달다.", author: "루소" },
    { text: "노력은 배신하지 않는다.", author: "한국 격언" },
    { text: "백지장도 맞들면 낫다.", author: "한국 속담" },
    { text: "천 리 길도 한 걸음부터.", author: "노자" },
    { text: "말 한마디로 천 냥 빚을 갚는다.", author: "한국 속담" },
    { text: "가는 말이 고와야 오는 말이 곱다.", author: "한국 속담" },
    { text: "웃는 얼굴에 침 뱉으랴.", author: "한국 속담" },
    { text: "건강한 신체에 건강한 정신이 깃든다.", author: "유베날리스" },
    { text: "일찍 일어나는 새가 벌레를 잡는다.", author: "윌리엄 캠든" },
    { text: "시간이 약이다.", author: "서양 속담" },
    { text: "아는 것이 힘이다.", author: "프랜시스 베이컨" },
    { text: "빈 수레가 요란하다.", author: "한국 속담" },
    { text: "급할수록 돌아가라.", author: "한국 속담" },
    { text: "티끌 모아 태산.", author: "한국 속담" },
    { text: "등잔 밑이 어둡다.", author: "한국 속담" },
    { text: "원숭이도 나무에서 떨어진다.", author: "한국 속담" },
    { text: "돌다리도 두들겨 보고 건너라.", author: "한국 속담" },
    { text: "호랑이 굴에 들어가야 호랑이를 잡는다.", author: "한국 속담" },
    { text: "비 온 뒤에 땅이 굳어진다.", author: "한국 속담" },
    { text: "개천에서 용 난다.", author: "한국 속담" },
    { text: "뛰는 놈 위에 나는 놈 있다.", author: "한국 속담" },
    { text: "세월은 사람을 기다려주지 않는다.", author: "도연명" },
    { text: "하루라도 책을 읽지 않으면 입안에 가시가 돋는다.", author: "안중근" },
    { text: "소년은 늙기 쉽고 학문은 이루기 어렵다.", author: "주희" },
    { text: "정직은 최선의 방책이다.", author: "세르반테스" },
    { text: "필요는 발명의 어머니.", author: "플라톤" },
    { text: "약속은 빚이다.", author: "독일 속담" },
    { text: "침묵은 금이다.", author: "칼라일" },
    { text: "펜은 칼보다 강하다.", author: "에드워드 불워 리턴" },
    { text: "역사는 되풀이된다.", author: "투키디데스" },
    { text: "모든 길은 로마로 통한다.", author: "라 퐁텐" },
    { text: "로마는 하루아침에 이루어지지 않았다.", author: "세르반테스" },
    { text: "지렁이도 밟으면 꿈틀한다.", author: "한국 속담" },
    { text: "구슬이 서 말이라도 꿰어야 보배.", author: "한국 속담" },
    { text: "쇠뿔도 단김에 빼라.", author: "한국 속담" },
    { text: "시작이 좋으면 끝도 좋다.", author: "독일 속담" },
    { text: "고생 끝에 낙이 온다.", author: "한국 속담" },
    { text: "열 번 찍어 안 넘어가는 나무 없다.", author: "한국 속담" },
    { text: "작은 고추가 맵다.", author: "한국 속담" },
    { text: "아니 땐 굴뚝에 연기 날까.", author: "한국 속담" },
    { text: "낮말은 새가 듣고 밤말은 쥐가 듣는다.", author: "한국 속담" },
    { text: "말이 씨가 된다.", author: "한국 속담" },
    { text: "호랑이도 제 말 하면 온다.", author: "한국 속담" },
    { text: "서당 개 삼 년이면 풍월을 읊는다.", author: "한국 속담" },
    { text: "하늘이 무너져도 솟아날 구멍이 있다.", author: "한국 속담" },
    { text: "소 잃고 외양간 고친다.", author: "한국 속담" },
    { text: "우물 안 개구리.", author: "한국 속담" },
    { text: "누워서 떡 먹기.", author: "한국 속담" },
    { text: "그림의 떡.", author: "한국 속담" },
    { text: "금강산도 식후경.", author: "한국 속담" },
    { text: "내 코가 석 자.", author: "한국 속담" },
    { text: "남의 떡이 더 커 보인다.", author: "서양 속담" },
    { text: "친구를 보면 그 사람을 알 수 있다.", author: "미상" },
    { text: "책은 마음의 양식이다.", author: "미상" },
    { text: "운동은 건강의 근원이다.", author: "미상" },
    { text: "웃음은 최고의 보약이다.", author: "미상" },
    { text: "사랑은 눈물의 씨앗.", author: "미상" },
    { text: "젊음은 다시 오지 않는다.", author: "미상" },
    { text: "시간은 돈이다.", author: "벤자민 프랭클린" },
    { text: "습관은 제2의 천성이다.", author: "시세로" },
    { text: "고통 없이는 얻는 것도 없다.", author: "벤자민 프랭클린" },
    { text: "연습이 완벽을 만든다.", author: "미상" },
    { text: "백문이 불여일견.", author: "반고" },
    { text: "과유불급.", author: "공자" },
    { text: "일체유심조.", author: "화엄경" },
    { text: "역지사지.", author: "맹자" },
    { text: "유비무환.", author: "서경" },
    { text: "대기만성.", author: "노자" },
    { text: "사필귀정.", author: "미상" },
    { text: "권선징악.", author: "미상" },
    { text: "새옹지마.", author: "회남자" },
    { text: "온고지신.", author: "논어" },
    { text: "타산지석.", author: "시경" },
    { text: "청출어람.", author: "순자" },
    { text: "형설지공.", author: "진서" },
    { text: "마부작침.", author: "당서" },
    { text: "우공이산.", author: "열자" },
    { text: "자승자박.", author: "한서" },
    { text: "자업자득.", author: "불경" },
    { text: "각골난망.", author: "미상" },
    { text: "결자해지.", author: "홍만종" },
    { text: "고진감래.", author: "미상" },
    { text: "괄목상대.", author: "삼국지" },
    { text: "군계일학.", author: "진서" },
    { text: "금의환향.", author: "미상" },
    { text: "다다익선.", author: "사기" },
    { text: "동문서답.", author: "미상" },
    { text: "동병상련.", author: "오월춘추" },
    { text: "동상이몽.", author: "미상" },
    { text: "막상막하.", author: "미상" },
    { text: "무용지물.", author: "장자" },
    { text: "문전성시.", author: "한서" },
    { text: "배은망덕.", author: "미상" },
    { text: "백발백중.", author: "사기" },
    { text: "부전자전.", author: "미상" },
    { text: "비일비재.", author: "미상" },
    { text: "사면초가.", author: "사기" },
    { text: "산전수전.", author: "미상" },
    { text: "삼고초려.", author: "삼국지" },
    { text: "상부상조.", author: "미상" },
    { text: "설상가상.", author: "미상" },
    { text: "속수무책.", author: "미상" },
    { text: "수수방관.", author: "미상" },
    { text: "식은 죽 먹기.", author: "미상" },
    { text: "심사숙고.", author: "미상" },
    { text: "십시일반.", author: "미상" },
    { text: "아전인수.", author: "미상" },
    { text: "악전고투.", author: "미상" },
    { text: "안하무인.", author: "미상" },
    { text: "약방의 감초.", author: "미상" },
    { text: "어부지리.", author: "전국책" },
    { text: "언감생심.", author: "미상" },
    { text: "오리무중.", author: "후한서" },
    { text: "오비이락.", author: "미상" },
    { text: "요지부동.", author: "미상" },
    { text: "용두사미.", author: "미상" },
    { text: "우왕좌왕.", author: "미상" },
    { text: "유명무실.", author: "미상" },
    { text: "유유상종.", author: "미상" },
    { text: "이심전심.", author: "미상" },
    { text: "이열치열.", author: "미상" },
    { text: "인과응보.", author: "불경" },
    { text: "일거양득.", author: "미상" },
    { text: "일구이언.", author: "미상" },
    { text: "일석이조.", author: "미상" },
    { text: "일취월장.", author: "시경" },
    { text: "일편단심.", author: "포은집" },
    { text: "임기응변.", author: "미상" },
    { text: "자포자기.", author: "맹자" },
    { text: "작심삼일.", author: "미상" },
    { text: "적반하장.", author: "미상" },
    { text: "전화위복.", author: "전국책" },
    { text: "절치부심.", author: "사기" },
    { text: "조삼모사.", author: "열자" },
    { text: "주객전도.", author: "미상" },
    { text: "주경야독.", author: "미상" },
    { text: "죽마고우.", author: "세설신어" },
    { text: "진퇴양난.", author: "시경" },
    { text: "천년만년.", author: "미상" },
    { text: "천생연분.", author: "미상" },
    { text: "천우신조.", author: "미상" },
    { text: "파죽지세.", author: "진서" },
    { text: "풍전등화.", author: "미상" },
    { text: "학수고대.", author: "미상" },
    { text: "함흥차사.", author: "미상" },
    { text: "해피엔딩.", author: "미상" },
    { text: "허심탄회.", author: "미상" },
    { text: "호사다마.", author: "미상" },
    { text: "환골탈태.", author: "노군전" },
    { text: "횡설수설.", author: "미상" },
    { text: "후회막급.", author: "미상" },
    { text: "희로애락.", author: "미상" },
    { text: "삶은 아름다워.", author: "미상" },
    { text: "오늘은 좋은 날.", author: "미상" },
    { text: "나는 할 수 있어.", author: "미상" },
    { text: "포기하지 마.", author: "미상" },
    { text: "힘내.", author: "미상" },
    { text: "사랑해.", author: "미상" },
    { text: "감사해.", author: "미상" },
    { text: "미안해.", author: "미상" },
    { text: "괜찮아.", author: "미상" },
    { text: "잘했어.", author: "미상" },
    { text: "멋져.", author: "미상" },
    { text: "최고야.", author: "미상" },
    { text: "행운을 빌어.", author: "미상" },
    { text: "축하해.", author: "미상" },
    { text: "반가워.", author: "미상" },
    { text: "어서 와.", author: "미상" },
    { text: "나중에 봐.", author: "미상" },
    { text: "안녕.", author: "미상" },
    { text: "잘 가.", author: "미상" },
    { text: "또 봐.", author: "미상" },
    { text: "좋은 아침.", author: "미상" },
    { text: "좋은 밤.", author: "미상" },
    { text: "잘 자.", author: "미상" },
    { text: "맛있게 먹어.", author: "미상" },
    { text: "배고파.", author: "미상" },
    { text: "배불러.", author: "미상" },
    { text: "졸려.", author: "미상" },
    { text: "일어나.", author: "미상" },
    { text: "씻어.", author: "미상" },
    { text: "입어.", author: "미상" },
    { text: "나가자.", author: "미상" },
    { text: "놀자.", author: "미상" },
    { text: "공부해.", author: "미상" },
    { text: "일해.", author: "미상" },
    { text: "쉬어.", author: "미상" },
    { text: "생각해.", author: "미상" },
    { text: "느껴봐.", author: "미상" },
    { text: "들어봐.", author: "미상" },
    { text: "봐봐.", author: "미상" },
    { text: "말해봐.", author: "미상" },
    { text: "써봐.", author: "미상" },
    { text: "읽어봐.", author: "미상" },
    { text: "배워봐.", author: "미상" },
    { text: "가르쳐줘.", author: "미상" },
    { text: "도와줘.", author: "미상" },
    { text: "함께해.", author: "미상" },
    { text: "혼자야.", author: "미상" },
    { text: "외로워.", author: "미상" },
    { text: "슬퍼.", author: "미상" },
    { text: "기뻐.", author: "미상" },
    { text: "화나.", author: "미상" },
    { text: "무서워.", author: "미상" },
    { text: "놀라워.", author: "미상" },
    { text: "궁금해.", author: "미상" },
    { text: "재밌어.", author: "미상" },
    { text: "지루해.", author: "미상" },
    { text: "피곤해.", author: "미상" },
    { text: "아파.", author: "미상" },
    { text: "나았어.", author: "미상" },
    { text: "건강해.", author: "미상" },
    { text: "행복해.", author: "미상" },
    { text: "불행해.", author: "미상" },
    { text: "성공해.", author: "미상" },
    { text: "실패해.", author: "미상" },
    { text: "이겨.", author: "미상" },
    { text: "져.", author: "미상" },
    { text: "비겨.", author: "미상" },
    { text: "달려.", author: "미상" },
    { text: "걸어.", author: "미상" },
    { text: "멈춰.", author: "미상" },
    { text: "가.", author: "미상" },
    { text: "와.", author: "미상" },
    { text: "올라가.", author: "미상" },
    { text: "내려가.", author: "미상" },
    { text: "들어가.", author: "미상" },
    { text: "나와.", author: "미상" },
    { text: "열어.", author: "미상" },
    { text: "닫아.", author: "미상" },
    { text: "켜.", author: "미상" },
    { text: "꺼.", author: "미상" },
    { text: "밀어.", author: "미상" },
    { text: "당겨.", author: "미상" },
    { text: "잡아.", author: "미상" },
    { text: "놓아.", author: "미상" },
    { text: "던져.", author: "미상" },
    { text: "받아.", author: "미상" },
    { text: "차.", author: "미상" },
    { text: "막아.", author: "미상" },
    { text: "때려.", author: "미상" },
    { text: "맞아.", author: "미상" },
    { text: "피해.", author: "미상" },
    { text: "숨어.", author: "미상" },
    { text: "찾아.", author: "미상" },
    { text: "봐.", author: "미상" },
    { text: "안 봐.", author: "미상" },
    { text: "들려.", author: "미상" },
    { text: "안 들려.", author: "미상" },
    { text: "냄새나.", author: "미상" },
    { text: "맛있어.", author: "미상" },
    { text: "맛없어.", author: "미상" },
    { text: "달아.", author: "미상" },
    { text: "써.", author: "미상" },
    { text: "셔.", author: "미상" },
    { text: "짜.", author: "미상" },
    { text: "매워.", author: "미상" },
    { text: "뜨거워.", author: "미상" },
    { text: "차가워.", author: "미상" },
    { text: "따뜻해.", author: "미상" },
    { text: "시원해.", author: "미상" },
    { text: "맑아.", author: "미상" },
    { text: "흐려.", author: "미상" },
    { text: "비 와.", author: "미상" },
    { text: "눈 와.", author: "미상" },
    { text: "바람 불어.", author: "미상" },
    { text: "천둥 쳐.", author: "미상" },
    { text: "번개 쳐.", author: "미상" },
    { text: "태풍 와.", author: "미상" },
    { text: "지진 나.", author: "미상" },
    { text: "불 나.", author: "미상" },
    { text: "물 난리.", author: "미상" },
    { text: "가뭄.", author: "미상" },
    { text: "풍년.", author: "미상" },
    { text: "흉년.", author: "미상" },
    { text: "봄.", author: "미상" },
    { text: "여름.", author: "미상" },
    { text: "가을.", author: "미상" },
    { text: "겨울.", author: "미상" },
    { text: "아침.", author: "미상" },
    { text: "점심.", author: "미상" },
    { text: "저녁.", author: "미상" },
    { text: "밤.", author: "미상" },
    { text: "새벽.", author: "미상" },
    { text: "오늘.", author: "미상" },
    { text: "내일.", author: "미상" },
    { text: "모레.", author: "미상" },
    { text: "어제.", author: "미상" },
    { text: "그저께.", author: "미상" },
    { text: "작년.", author: "미상" },
    { text: "올해.", author: "미상" },
    { text: "내년.", author: "미상" },
    { text: "월요일.", author: "미상" },
    { text: "화요일.", author: "미상" },
    { text: "수요일.", author: "미상" },
    { text: "목요일.", author: "미상" },
    { text: "금요일.", author: "미상" },
    { text: "토요일.", author: "미상" },
    { text: "일요일.", author: "미상" },
    { text: "주말.", author: "미상" },
    { text: "평일.", author: "미상" },
    { text: "휴일.", author: "미상" },
    { text: "공휴일.", author: "미상" },
    { text: "명절.", author: "미상" },
    { text: "설날.", author: "미상" },
    { text: "추석.", author: "미상" },
    { text: "크리스마스.", author: "미상" },
    { text: "생일.", author: "미상" },
    { text: "기념일.", author: "미상" },
    { text: "결혼식.", author: "미상" },
    { text: "장례식.", author: "미상" },
    { text: "졸업식.", author: "미상" },
    { text: "입학식.", author: "미상" },
    { text: "방학.", author: "미상" },
    { text: "개학.", author: "미상" },
    { text: "소풍.", author: "미상" },
    { text: "여행.", author: "미상" },
    { text: "출장.", author: "미상" },
    { text: "이사.", author: "미상" },
    { text: "청소.", author: "미상" },
    { text: "빨래.", author: "미상" },
    { text: "요리.", author: "미상" },
    { text: "설거지.", author: "미상" },
    { text: "장보기.", author: "미상" },
    { text: "산책.", author: "미상" },
    { text: "조깅.", author: "미상" },
    { text: "수영.", author: "미상" },
    { text: "등산.", author: "미상" },
    { text: "낚시.", author: "미상" },
    { text: "캠핑.", author: "미상" },
    { text: "영화.", author: "미상" },
    { text: "음악.", author: "미상" },
    { text: "독서.", author: "미상" },
    { text: "그림.", author: "미상" },
    { text: "사진.", author: "미상" },
    { text: "게임.", author: "미상" },
    { text: "인터넷.", author: "미상" },
    { text: "쇼핑.", author: "미상" },
    { text: "드라이브.", author: "미상" },
    { text: "데이트.", author: "미상" },
    { text: "파티.", author: "미상" },
    { text: "모임.", author: "미상" },
    { text: "회식.", author: "미상" },
    { text: "수다.", author: "미상" },
    { text: "싸움.", author: "미상" },
    { text: "화해.", author: "미상" },
    { text: "이별.", author: "미상" },
    { text: "만남.", author: "미상" },
    { text: "약속.", author: "미상" },
    { text: "선물.", author: "미상" },
    { text: "편지.", author: "미상" },
    { text: "전화.", author: "미상" },
    { text: "문자.", author: "미상" },
    { text: "이메일.", author: "미상" },
    { text: "SNS.", author: "미상" },
    { text: "뉴스.", author: "미상" },
    { text: "날씨.", author: "미상" },
    { text: "교통.", author: "미상" },
    { text: "운세.", author: "미상" },
    { text: "로또.", author: "미상" },
    { text: "주식.", author: "미상" },
    { text: "부동산.", author: "미상" },
    { text: "적금.", author: "미상" },
    { text: "보험.", author: "미상" },
    { text: "세금.", author: "미상" },
    { text: "월급.", author: "미상" },
    { text: "용돈.", author: "미상" },
    { text: "빚.", author: "미상" },
    { text: "환율.", author: "미상" },
    { text: "물가.", author: "미상" },
    { text: "경제.", author: "미상" },
    { text: "정치.", author: "미상" },
    { text: "사회.", author: "미상" },
    { text: "문화.", author: "미상" },
    { text: "역사.", author: "미상" },
    { text: "과학.", author: "미상" },
    { text: "기술.", author: "미상" },
    { text: "환경.", author: "미상" },
    { text: "교육.", author: "미상" },
    { text: "종교.", author: "미상" },
    { text: "철학.", author: "미상" },
    { text: "예술.", author: "미상" },
    { text: "체육.", author: "미상" },
    { text: "건강.", author: "미상" },
    { text: "사랑.", author: "미상" },
    { text: "우정.", author: "미상" },
    { text: "가족.", author: "미상" },
    { text: "이웃.", author: "미상" },
    { text: "직장.", author: "미상" },
    { text: "학교.", author: "미상" },
    { text: "나라.", author: "미상" },
    { text: "세계.", author: "미상" },
    { text: "우주.", author: "미상" },
    { text: "자연.", author: "미상" },
    { text: "인생.", author: "미상" },
];

export function getDailyQuote(): Quote {
    // 현재 날짜를 기준으로 인덱스 생성 (UTC 기준)
    // 클라이언트 사이드에서도 동일한 결과를 보여주기 위해 날짜 문자열 사용
    const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

    // 간단한 해시 함수: 날짜 문자열의 각 문자의 코드값을 더함
    let hash = 0;
    for (let i = 0; i < today.length; i++) {
        hash = today.charCodeAt(i) + ((hash << 5) - hash);
    }

    // 음수 처리 및 배열 길이로 모듈러 연산
    const index = Math.abs(hash) % quotes.length;

    return quotes[index];
}
