export interface Quote {
    text: string;
    author: string;
    textEn?: string;
    authorEn?: string;
}

export const quotes: Quote[] = [
    {
        text: "인생은 폭풍우가 지나가기를 기다리는 것이 아니라, 빗속에서 춤추는 법을 배우는 것이다.",
        author: "비비안 그린",
        textEn: "Life isn't about waiting for the storm to pass, it's about learning to dance in the rain.",
        authorEn: "Vivian Greene"
    },
    {
        text: "나를 죽이지 못하는 고통은 나를 더 강하게 만든다.",
        author: "프리드리히 니체",
        textEn: "That which does not kill us makes us stronger.",
        authorEn: "Friedrich Nietzsche"
    },
    {
        text: "너 자신의 무지를 절대 과소평가하지 마라.",
        author: "알베르트 아인슈타인",
        textEn: "Never underestimate your own ignorance.",
        authorEn: "Albert Einstein"
    },
    {
        text: "가장 위대한 영광은 한 번도 실패하지 않음이 아니라, 실패할 때마다 다시 일어서는 데 있다.",
        author: "공자",
        textEn: "Our greatest glory is not in never falling, but in rising every time we fall.",
        authorEn: "Confucius"
    },
    {
        text: "남을 아는 자는 지혜롭고, 자기를 아는 자는 명철하다.",
        author: "노자",
        textEn: "He who knows others is wise; he who knows himself is enlightened.",
        authorEn: "Lao Tzu"
    },
    { text: "어디를 가든지 마음을 다해 가라.", author: "공자", textEn: "Wheresoever you go, go with all your heart.", authorEn: "Confucius" },
    { text: "자신을 사랑하는 법을 아는 것이 가장 위대한 사랑이다.", author: "마이클 휘트니", textEn: "Learning to love yourself is the greatest love of all.", authorEn: "Michael Whitney" },
    { text: "행복은 이미 만들어진 것이 아니다. 당신의 행동에서 비롯된다.", author: "달라이 라마", textEn: "Happiness is not something ready made. It comes from your own actions.", authorEn: "Dalai Lama" },
    { text: "어두움을 저주하는 것보다는 촛불 하나를 켜는 것이 낫다.", author: "공자", textEn: "Better to light a candle than to curse the darkness.", authorEn: "Confucius" },
    { text: "우리가 하는 일은 바다에 붓는 물 한 방울에 불과하지만, 그 한 방울이 없다면 바다는 그만큼 줄어들 것이다.", author: "마더 테레사", textEn: "We ourselves feel that what we are doing is just a drop in the ocean. But the ocean would be less because of that missing drop.", authorEn: "Mother Teresa" },
    { text: "변화는 필연적이다. 성장은 선택이다.", author: "존 맥스웰", textEn: "Change is inevitable. Growth is optional.", authorEn: "John Maxwell" },
    { text: "상처받은 치유자만이 진정으로 치유할 수 있다.", author: "칼 융", textEn: "Only the wounded healer can truly heal.", authorEn: "Carl Jung" },
    { text: "너의 시야는 너의 마음을 들여다볼 때만 맑아질 것이다. 밖을 보는 자는 꿈을 꾸고, 안을 보는 자는 깨어난다.", author: "칼 융", textEn: "Your vision will become clear only when you can look into your own heart. Who looks outside, dreams; who looks inside, awakes.", authorEn: "Carl Jung" },
    { text: "인생은 자전거를 타는 것과 같다. 균형을 잡으려면 계속 움직여야 한다.", author: "알베르트 아인슈타인", textEn: "Life is like riding a bicycle. To keep your balance, you must keep moving.", authorEn: "Albert Einstein" },
    { text: "중요한 것은 멈추지 않고 질문하는 것이다.", author: "알베르트 아인슈타인", textEn: "The important thing is not to stop questioning.", authorEn: "Albert Einstein" },
    { text: "내일의 꽃은 오늘의 씨앗 속에 있다.", author: "속담", textEn: "The flowers of tomorrow are in the seeds of today.", authorEn: "Proverb" },
    { text: "조용한 마음이 묻는다. 걱정해서 해결될 일인가? 아니라면 왜 걱정하는가.", author: "티베트 속담", textEn: "A quiet mind asks: Is this something that can be resolved by worrying? If not, why worry?", authorEn: "Tibetan Proverb" },
    { text: "진정한 발견은 새로운 땅을 찾는 것이 아니라 새로운 눈을 갖는 것이다.", author: "마르셀 프루스트", textEn: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", authorEn: "Marcel Proust" },
    { text: "너무 소심하고 까다롭게 자신의 행동을 고민하지 말라. 인생은 실험이다.", author: "랄프 왈도 에머슨", textEn: "Do not be too timid and squeamish about your actions. All life is an experiment.", authorEn: "Ralph Waldo Emerson" },
    { text: "그대가 오랫동안 심연을 들여다보면 심연 또한 그대를 들여다본다.", author: "프리드리히 니체", textEn: "And if you gaze long enough into an abyss, the abyss will gaze back into you.", authorEn: "Friedrich Nietzsche" },
    { text: "삶이 있는 한 희망은 있다.", author: "키케로", textEn: "While there's life, there's hope.", authorEn: "Cicero" },
    { text: "산다는 것은 숨쉬는 것이 아니라 행동하는 것이다.", author: "루소", textEn: "To live is not to breathe but to act.", authorEn: "Rousseau" },
    { text: "언제나 현재에 집중할 수 있다면 행복할 것이다.", author: "파울로 코엘료", textEn: "If you can always concentrate on the present, you'll be a happy man.", authorEn: "Paulo Coelho" },
    { text: "신은 용기 있는 자를 결코 버리지 않는다.", author: "켄러", textEn: "God never abandons the courageous.", authorEn: "Kenner" },
    { text: "피할 수 없으면 즐겨라.", author: "로버트 엘리엇", textEn: "If you can't avoid it, enjoy it.", authorEn: "Robert Eliot" },
    { text: "단순하게 살아라. 현대인은 쓸데없는 절차와 일 때문에 얼마나 복잡한 삶을 살아가는가?", author: "이드리스 샤흐", textEn: "Live simply. How complicated life becomes for modern people due to useless procedures and tasks?", authorEn: "Idries Shah" },
    { text: "먼저 자신을 비웃어라. 다른 사람이 당신을 비웃기 전에.", author: "엘사 맥스웰", textEn: "Laugh at yourself first, before anyone else can.", authorEn: "Elsa Maxwell" },
    { text: "먼저핀 꽃은 먼저 진다 남보다 먼저 공을 세우려고 조급히 서둘지 마라.", author: "채근담", textEn: "Flowers that bloom early fade early. Do not rush to achieve merit before others.", authorEn: "Caigentan (Vegetable Roots Discourse)" },
    { text: "행복한 삶을 살기 위해 필요한 것은 거의 없다.", author: "마르쿠스 아우렐리우스", textEn: "Very little is needed to make a happy life.", authorEn: "Marcus Aurelius" },
    { text: "절대 포기하지 마라. 당신이 되고 싶은 무언가가 있다면, 그에 대해 자부심을 가져라.", author: "엠마 톰슨", textEn: "Never give up. If there's something you want to be, take pride in it.", authorEn: "Emma Thompson" },
    { text: "계단을 밟아야 계단 위에 올라설수 있다.", author: "터키속담", textEn: "You must climb the stairs to reach the top.", authorEn: "Turkish Proverb" },
    { text: "오랫동안 꿈을 그리는 사람은 마침내 그 꿈을 닮아 간다.", author: "앙드레 말로", textEn: "He who dreams for a long time eventually resembles his dream.", authorEn: "Andre Malraux" },
    { text: "좋은 성과를 얻으려면 한 걸음 한 걸음이 힘차고 충실하지 않으면 안 된다.", author: "단테", textEn: "To achieve great results, each step must be strong and faithful.", authorEn: "Dante" },
    { text: "행복은 습관이다, 그것을 몸에 지니라.", author: "허버드", textEn: "Happiness is a habit—cultivate it.", authorEn: "Hubbard" },
    { text: "자신감 있는 표정을 지으면 자신감이 생긴다.", author: "찰스다윈", textEn: "Wearing a confident expression creates confidence.", authorEn: "Charles Darwin" },
    { text: "평생 살 것처럼 꿈을 꾸고, 내일 죽을 것처럼 오늘을 살아라.", author: "제임스 딘", textEn: "Dream as if you'll live forever. Live as if you'll die today.", authorEn: "James Dean" },
    { text: "성공의 비결은 단 한 가지, 잘할 수 있는 일에 광적으로 집중하는 것이다.", author: "톰 모나건", textEn: "The secret of success is to concentrate fanatically on the one thing you can do well.", authorEn: "Tom Monaghan" },
    { text: "꿈을 계속 간직하고 있으면 반드시 실현할 때가 온다.", author: "괴테", textEn: "If you keep holding onto your dream, the time will come when it will be realized.", authorEn: "Goethe" },
    { text: "문제는 목적지에 얼마나 빨리 가느냐가 아니라 그 목적지가 어디냐는 것이다.", author: "도서 '인생' 중", textEn: "The question is not how fast you get to the destination, but where the destination is.", authorEn: "From the book 'Life'" },
    { text: "겨울이 오면 봄이 멀지 않으리.", author: "셸리", textEn: "If Winter comes, can Spring be far behind?", authorEn: "Shelley" },
    { text: "인생이란 학교에는 불행 이라는 훌륭한 스승이 있다.", author: "프리체", textEn: "In the school of life, there is an excellent teacher called misfortune.", authorEn: "Fritche" },
    { text: "알면서 행하지 않는 것은 모르는 것과 다름없다.", author: "왕양명", textEn: "To know and not to act is the same as not knowing.", authorEn: "Wang Yangming" },
    { text: "길을 잃는다는 것은 곧 길을 알게 된다는 것이다.", author: "동아프리카속담", textEn: "To get lost is to learn the way.", authorEn: "East African Proverb" },
    { text: "기회는 새와 같은 것, 날아가기 전에 잡아라.", author: "스마일즈", textEn: "Opportunity is like a bird; catch it before it flies away.", authorEn: "Smiles" },
    { text: "타인을 돕는 것이야말로 진정한 삶의 예술이다.", author: "빈센트 반 고흐", textEn: "Helping others is the true art of life.", authorEn: "Vincent Van Gogh" },
    { text: "행복의 한 쪽 문이 닫히면 다른 쪽 문이 열린다. 그러나 흔히 우리는 닫혀진 문을 오랫동안 보기 때문에 우리를 위해 열려 있는 문을 보지 못한다.", author: "헬렌 켈러", textEn: "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", authorEn: "Helen Keller" },
    { text: "해야 할 것을 하라. 모든 것은 타인의 행복을 위해서, 동시에 특히 나의 행복을 위해서이다.", author: "톨스토이", textEn: "Do what needs to be done. All for the happiness of others, and concurrently, especially for my own happiness.", authorEn: "Tolstoy" },
    { text: "작은 기회로부터 종종 위대한 업적이 시작된다.", author: "데모스테네스", textEn: "Great achievements often start from small opportunities.", authorEn: "Demosthenes" },
    { text: "최고에 도달하려면 최저에서 시작하라.", author: "P.시루스", textEn: "To reach the highest, begin at the lowest.", authorEn: "Publilius Syrus" },
    { text: "삶을 사는 데는 단 두 가지 방법이 있다. 하나는 기적이 전혀 없다고 믿는 것이고, 또 다른 하나는 모든 것이 기적이라고 믿는 것이다.", author: "알베르트 아인슈타인", textEn: "There are only two ways to live your life. One is as though nothing is a miracle. The other is as though everything is a miracle.", authorEn: "Albert Einstein" },
    { text: "당신이 할 수 있다고 믿든 할 수 없다고 믿든, 믿는 대로 될 것이다.", author: "헨리 포드", textEn: "Whether you think you can, or you think you can't – you're right.", authorEn: "Henry Ford" },
    { text: "세상은 고통으로 가득하지만, 그것을 극복하는 사람들로도 가득하다.", author: "헬렌 켈러", textEn: "Although the world is full of suffering, it is also full of the overcoming of it.", authorEn: "Helen Keller" },
    { text: "도전은 인생을 흥미롭게 만들며, 도전의 극복이 인생을 의미 있게 한다.", author: "조슈아 J. 마린", textEn: "Challenges make life interesting and overcoming them makes life meaningful.", authorEn: "Joshua J. Marine" },
    { text: "위대한 이들은 목적을 갖고, 그 외의 사람들은 소원을 갖는다.", author: "워싱턴 어빙", textEn: "Great minds have purposes; others have wishes.", authorEn: "Washington Irving" },
    { text: "당신의 인생은 당신이 하루종일 무슨 생각을 하는지에 달려있다.", author: "랄프 왈도 에머슨", textEn: "A man is what he thinks about all day long.", authorEn: "Ralph Waldo Emerson" },
    { text: "성공은 매일 반복되는 작은 노력들의 합이다.", author: "로버트 콜리어", textEn: "Success is the sum of small efforts, repeated day in and day out.", authorEn: "Robert Collier" },
    { text: "시작이 반이다.", author: "아리스토텔레스", textEn: "Well begun is half done.", authorEn: "Aristotle" },
    { text: "실패는 성공을 위한 리허설이다.", author: "어니 J. 젤린스키", textEn: "failure is a rehearsal for success.", authorEn: "Ernie J. Zelinski" },
    { text: "나만이 내 인생을 바꿀 수 있다. 아무도 날 대신해 해줄 수 없다.", author: "캐롤 버넷", textEn: "Only I can change my life. No one can do it for me.", authorEn: "Carol Burnett" },
    { text: "웃음 없는 하루는 낭비한 하루다.", author: "찰리 채플린", textEn: "A day without laughter is a day wasted.", authorEn: "Charlie Chaplin" },
    { text: "스스로를 존경하면 다른 사람도 당신을 존경할 것이다.", author: "공자", textEn: "Respect yourself and others will respect you.", authorEn: "Confucius" },
    { text: "무례한 사람의 행위는 내 행위가 아니니 내 버려두라.", author: "법정 스님", textEn: "The rude actions of others are not my actions, so let them be.", authorEn: "Venerable Beopjeong" },
    { text: "가장 큰 위험은 위험 없는 삶이다.", author: "스티븐 코비", textEn: "The greatest risk is the risk of riskless living.", authorEn: "Stephen Covey" },
    { text: "시간은 인간이 쓸 수 있는 가장 값진 것이다.", author: "테오프라스토스", textEn: "Time is the most valuable thing a man can spend.", authorEn: "Theophrastus" },
    { text: "당신이 있는 곳에서, 당신이 가진 것으로, 당신이 할 수 있는 것을 하라.", author: "테디 루즈벨트", textEn: "Do what you can, with what you have, where you are.", authorEn: "Teddy Roosevelt" },
    { text: "행복은 목적지가 아니라 여정이다.", author: "소크라테스", textEn: "Happiness is not a destination, but a journey.", authorEn: "Socrates" },
    { text: "다른 사람의 삶을 사느라 시간을 낭비하지 마라.", author: "스티브 잡스", textEn: "Don't waste your time living someone else's life.", authorEn: "Steve Jobs" },
    { text: "인내심을 가져라. 모든 것은 쉬워지기 전에는 어렵다.", author: "사디", textEn: "Have patience. All things are difficult before they become easy.", authorEn: "Saadi" },
    { text: "침묵은 때로 가장 강력한 외침이다.", author: "영화 '인생은 아름다워'", textEn: "Silence is sometimes the most powerful scream.", authorEn: "Movie 'Life is Beautiful'" },
    { text: "나무를 심기에 가장 좋은 때는 20년 전이었다. 두 번째로 좋은 때는 바로 지금이다.", author: "중국 속담", textEn: "The best time to plant a tree was 20 years ago. The second best time is now.", authorEn: "Chinese Proverb" },
    { text: "바람이 불지 않으면 노를 저어라.", author: "윈스턴 처칠", textEn: "If the wind will not serve, take to the oars.", authorEn: "Winston Churchill" },
    { text: "인생에서 가장 큰 후회는 하지 않은 일들에 대한 것이다.", author: "마크 트웨인", textEn: "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do.", authorEn: "Mark Twain" },
    { text: "미래는 꿈의 아름다움을 믿는 자들의 것이다.", author: "엘리너 루즈벨트", textEn: "The future belongs to those who believe in the beauty of their dreams.", authorEn: "Eleanor Roosevelt" },
    { text: "성공이란 열정을 잃지 않고 실패에서 실패로 거듭 나아가는 능력이다.", author: "윈스턴 처칠", textEn: "Success consists of going from failure to failure without loss of enthusiasm.", authorEn: "Winston Churchill" },
    { text: "한계는 당신의 마음 속에만 존재한다.", author: "익명", textEn: "Limits exist only in the mind.", authorEn: "Anonymous" },
    { text: "오늘 걷지 않으면 내일은 뛰어야 한다.", author: "카를레스 푸욜", textEn: "If you do not walk today, you will have to run tomorrow.", authorEn: "Carles Puyol" },
    { text: "가장 어두운 밤이 가장 밝은 별을 만든다.", author: "도스토예프스키", textEn: "The darker the night, the brighter the stars.", authorEn: "Dostoevsky" },
    { text: "사람은 오로지 가슴으로만 올바르게 볼 수 있다. 본질적인 것은 눈에 보이지 않는다.", author: "생텍쥐페리", textEn: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.", authorEn: "Saint-Exupery" },
    { text: "모든 위대한 진리는 처음에는 신성모독으로 시작된다.", author: "조지 버나드 쇼", textEn: "All great truths begin as blasphemies.", authorEn: "George Bernard Shaw" },
    { text: "사랑은 우리가 가진 유일한, 시간과 공간을 초월하는 것이다.", author: "영화 '인터스텔라'", textEn: "Love is the one thing we're capable of perceiving that transcends dimensions of time and space.", authorEn: "Movie 'Interstellar'" },
    { text: "지금 잠을 자면 꿈을 꾸지만, 지금 공부하면 꿈을 이룬다.", author: "훈계", textEn: "Sleep now, you will be dreaming. Study now, you will be achieving your dream.", authorEn: "Adage" },
    { text: "독서가 정신에 미치는 영향은 운동이 신체에 미치는 영향과 같다.", author: "리처드 스틸", textEn: "Reading is to the mind what exercise is to the body.", authorEn: "Richard Steele" },
    { text: "모든 성취의 시작점은 갈망이다.", author: "나폴레온 힐", textEn: "The starting point of all achievement is desire.", authorEn: "Napoleon Hill" },
    { text: "천재는 1%의 영감과 99%의 땀으로 이루어진다.", author: "에디슨", textEn: "Genius is one percent inspiration and ninety-nine percent perspiration.", authorEn: "Thomas Edison" },
    { text: "희망은 깨어있는 꿈이다.", author: "아리스토텔레스", textEn: "Hope is a waking dream.", authorEn: "Aristotle" },
    { text: "너 자신이 되어라. 다른 사람은 이미 모두 누군가가 차지했다.", author: "오스카 와일드", textEn: "Be yourself; everyone else is already taken.", authorEn: "Oscar Wilde" },
    { text: "삶이란 우리의 인생관이 만들어내는 것이다.", author: "마르쿠스 아우렐리우스", textEn: "Our life is what our thoughts make it.", authorEn: "Marcus Aurelius" },
    { text: "우리는 우리가 반복적으로 하는 행동의 결과물이다.", author: "아리스토텔레스", textEn: "We are what we repeatedly do.", authorEn: "Aristotle" },
    { text: "불가능은 소심한 자들의 환상이다.", author: "나폴레옹", textEn: "Impossible is a word to be found only in the dictionary of fools.", authorEn: "Napoleon" },
    { text: "두려움은 희망 없이 있을 수 없고, 희망은 두려움 없이 있을 수 없다.", author: "바뤼흐 스피노자", textEn: "Fear cannot be without hope nor hope without fear.", authorEn: "Baruch Spinoza" },
    { text: "지혜는 경험의 딸이다.", author: "레오나르도 다빈치", textEn: "Wisdom is the daughter of experience.", authorEn: "Leonardo da Vinci" },
    { text: "교육은 세상을 바꿀 수 있는 가장 강력한 무기다.", author: "넬슨 만델라", textEn: "Education is the most powerful weapon which you can use to change the world.", authorEn: "Nelson Mandela" },
    { text: "친절은 언어장애인도 말할 수 있고 청각장애인도 들을 수 있는 언어다.", author: "마크 트웨인", textEn: "Kindness is the language which the deaf can hear and the blind can see.", authorEn: "Mark Twain" },
    { text: "사랑받고 싶다면 사랑하라, 그리고 사랑스럽게 행동하라.", author: "벤자민 프랭클린", textEn: "If you would be loved, love, and be loveable.", authorEn: "Benjamin Franklin" },
    { text: "평화는 미소에서 시작된다.", author: "마더 테레사", textEn: "Peace begins with a smile.", authorEn: "Mother Teresa" },
    { text: "진실은 결코 속이지 않는다.", author: "칸트", textEn: "Truth never deceives.", authorEn: "Immanuel Kant" },
    { text: "지식이 없는 성실은 약하고 소용없으며, 성실이 없는 지식은 위험하고 두렵다.", author: "사무엘 존슨", textEn: "Integrity without knowledge is weak and useless, and knowledge without integrity is dangerous and dreadful.", authorEn: "Samuel Johnson" },
    { text: "행동은 모든 성공의 기본 열쇠이다.", author: "파블로 피카소", textEn: "Action is the foundational key to all success.", authorEn: "Pablo Picasso" },
    { text: "준비하지 않은 자는 기회가 와도 소용없다.", author: "알렉시스 드 토크빌", textEn: "Chance favors only the prepared mind.", authorEn: "Alexis de Tocqueville" },
    { text: "기적은 대개 부지런한 노력에 대한 보답이다.", author: "그레이", textEn: "Miracles are generally the reward of industrious effort.", authorEn: "Gray" },
    { text: "겸손은 사람을 머물게 하고, 칭찬은 사람을 가깝게 하고, 넓음은 사람을 따르게 하고, 깊음은 사람을 감동케 한다.", author: "다산 정약용", textEn: "Humility makes people stay, praise makes people close, breadth makes people follow, and depth makes people moved.", authorEn: "Dasan Jeong Yak-yong" },
    { text: "말은 마음의 초상이다.", author: "존 레이", textEn: "Speech is the picture of the mind.", authorEn: "John Ray" },
    { text: "음악은 영혼의 산물이다.", author: "베토벤", textEn: "Music is the mediator between the spiritual and the sensual life.", authorEn: "Ludwig van Beethoven" },
    { text: "예술은 거짓을 통해 진실을 말한다.", author: "파블로 피카소", textEn: "Art is a lie that makes us realize truth.", authorEn: "Pablo Picasso" },
    { text: "자유는 책임이다. 그래서 대부분의 사람들은 자유를 두려워한다.", author: "조지 버나드 쇼", textEn: "Liberty means responsibility. That is why most men dread it.", authorEn: "George Bernard Shaw" },
    { text: "용기란 두려움이 없는 것이 아니라, 두려움보다 더 중요한 무언가가 있다는 판단이다.", author: "앰브로스 레드문", textEn: "Courage is not the absence of fear, but rather the judgment that something else is more important than fear.", authorEn: "Ambrose Redmoon" },
    { text: "성공한 사람이 되려 하기보다는 가치 있는 사람이 되려 하라.", author: "알베르트 아인슈타인", textEn: "Try not to become a man of success, but rather try to become a man of value.", authorEn: "Albert Einstein" },
    { text: "꿈을 이루기에 너무 늦은 나이란 없다.", author: "조지 엘리엇", textEn: "It is never too late to be what you might have been.", authorEn: "George Eliot" },
    { text: "인생은 과감한 모험이거나 아니면 아무것도 아니다.", author: "헬렌 켈러", textEn: "Life is either a daring adventure or nothing.", authorEn: "Helen Keller" },
    { text: "나만이 내 운명의 주인이요, 나만이 내 영혼의 선장이다.", author: "윌리엄 어니스트 헨리", textEn: "I am the master of my fate, I am the captain of my soul.", authorEn: "William Ernest Henley" },
    { text: "당신이 세상을 바꿀 수 있다고 생각할 만큼 미친 사람들이 결국 세상을 바꾼다.", author: "로브 실타넨", textEn: "The people who are crazy enough to think they can change the world are the ones who do.", authorEn: "Rob Siltanen" },
    { text: "어제의 나보다 더 나은 오늘의 내가 되어라.", author: "힌두 속담", textEn: "There is nothing noble in being superior to your fellow man; true nobility is being superior to your former self.", authorEn: "Hindu Proverb" },
    { text: "세상의 소금과 빛이 되어라.", author: "성경", textEn: "You are the salt of the earth... You are the light of the world.", authorEn: "Bible" },
    { text: "사랑은 모든 것을 이긴다.", author: "버질", textEn: "Love conquers all.", authorEn: "Virgil" },
    { text: "진정한 친구는 세상이 다 떠날 때 들어오는 사람이다.", author: "월터 윈첼", textEn: "A real friend is one who walks in when the rest of the world walks out.", authorEn: "Walter Winchell" },
    { text: "행복은 나누면 배가 된다.", author: "스웨덴 속담", textEn: "Happiness shared is doubled.", authorEn: "Swedish Proverb" },
    { text: "감사는 고결한 영혼의 얼굴이다.", author: "T. 제퍼슨", textEn: "Gratitude is the face of a noble soul.", authorEn: "Thomas Jefferson" },
    { text: "용서는 복수보다 낫다.", author: "피타쿠스", textEn: "Forgiveness is better than revenge.", authorEn: "Pittacus" },
    { text: "인내는 쓰지만 그 열매는 달다.", author: "루소", textEn: "Patience is bitter, but its fruit is sweet.", authorEn: "Jean-Jacques Rousseau" },
    { text: "노력은 배신하지 않는다.", author: "한국 격언", textEn: "Effort never betrays.", authorEn: "Korean Proverb" },
    { text: "백지장도 맞들면 낫다.", author: "한국 속담", textEn: "Many hands make light work.", authorEn: "Korean Proverb" },
    { text: "천 리 길도 한 걸음부터.", author: "노자", textEn: "A journey of a thousand miles begins with a single step.", authorEn: "Lao Tzu" },
    { text: "말 한마디로 천 냥 빚을 갚는다.", author: "한국 속담", textEn: "One good word can pay off a thousand debts.", authorEn: "Korean Proverb" },
    { text: "가는 말이 고와야 오는 말이 곱다.", author: "한국 속담", textEn: "Nice words for nice words.", authorEn: "Korean Proverb" },
    { text: "웃는 얼굴에 침 뱉으랴.", author: "한국 속담", textEn: "No one spits on a smiling face.", authorEn: "Korean Proverb" },
    { text: "건강한 신체에 건강한 정신이 깃든다.", author: "유베날리스", textEn: "A sound mind in a sound body.", authorEn: "Juvenal" },
    { text: "일찍 일어나는 새가 벌레를 잡는다.", author: "윌리엄 캠든", textEn: "The early bird catches the worm.", authorEn: "William Camden" },
    { text: "시간이 약이다.", author: "서양 속담", textEn: "Time heals all wounds.", authorEn: "Western Proverb" },
    { text: "아는 것이 힘이다.", author: "프랜시스 베이컨", textEn: "Knowledge is power.", authorEn: "Francis Bacon" },
    { text: "빈 수레가 요란하다.", author: "한국 속담", textEn: "Empty vessels make the most noise.", authorEn: "Korean Proverb" },
    { text: "급할수록 돌아가라.", author: "한국 속담", textEn: "More haste, less speed.", authorEn: "Korean Proverb" },
    { text: "티끌 모아 태산.", author: "한국 속담", textEn: "Little drops of water make the mighty ocean.", authorEn: "Korean Proverb" },
    { text: "등잔 밑이 어둡다.", author: "한국 속담", textEn: "It is darkest under the lamp.", authorEn: "Korean Proverb" },
    { text: "원숭이도 나무에서 떨어진다.", author: "한국 속담", textEn: "Even monkeys fall from trees.", authorEn: "Korean Proverb" },
    { text: "돌다리도 두들겨 보고 건너라.", author: "한국 속담", textEn: "Look before you leap.", authorEn: "Korean Proverb" },
    { text: "호랑이 굴에 들어가야 호랑이를 잡는다.", author: "한국 속담", textEn: "Nothing ventured, nothing gained.", authorEn: "Korean Proverb" },
    { text: "비 온 뒤에 땅이 굳어진다.", author: "한국 속담", textEn: "After the storm comes the calm.", authorEn: "Korean Proverb" },
    { text: "개천에서 용 난다.", author: "한국 속담", textEn: "Rags to riches.", authorEn: "Korean Proverb" },
    { text: "뛰는 놈 위에 나는 놈 있다.", author: "한국 속담", textEn: "There is always someone better.", authorEn: "Korean Proverb" },
    { text: "세월은 사람을 기다려주지 않는다.", author: "도연명", textEn: "Time and tide wait for no man.", authorEn: "Tao Yuanming" },
    { text: "하루라도 책을 읽지 않으면 입안에 가시가 돋는다.", author: "안중근", textEn: "If I do not read books for a day, thorns grow in my mouth.", authorEn: "Ahn Jung-geun" },
    { text: "소년은 늙기 쉽고 학문은 이루기 어렵다.", author: "주희", textEn: "Art is long, life is short.", authorEn: "Zhu Xi" },
    { text: "정직은 최선의 방책이다.", author: "세르반테스", textEn: "Honesty is the best policy.", authorEn: "Cervantes" },
    { text: "필요는 발명의 어머니.", author: "플라톤", textEn: "Necessity is the mother of invention.", authorEn: "Plato" },
    { text: "약속은 빚이다.", author: "독일 속담", textEn: "A promise is a debt.", authorEn: "German Proverb" },
    { text: "침묵은 금이다.", author: "칼라일", textEn: "Silence is golden.", authorEn: "Carlyle" },
    { text: "펜은 칼보다 강하다.", author: "에드워드 불워 리턴", textEn: "The pen is mightier than the sword.", authorEn: "Edward Bulwer-Lytton" },
    { text: "역사는 되풀이된다.", author: "투키디데스", textEn: "History repeats itself.", authorEn: "Thucydides" },
    { text: "모든 길은 로마로 통한다.", author: "라 퐁텐", textEn: "All roads lead to Rome.", authorEn: "La Fontaine" },
    { text: "로마는 하루아침에 이루어지지 않았다.", author: "세르반테스", textEn: "Rome was not built in a day.", authorEn: "Cervantes" },
    { text: "지렁이도 밟으면 꿈틀한다.", author: "한국 속담", textEn: "Even a worm will turn.", authorEn: "Korean Proverb" },
    { text: "구슬이 서 말이라도 꿰어야 보배.", author: "한국 속담", textEn: "Beads are not jewelry until strung together.", authorEn: "Korean Proverb" },
    { text: "쇠뿔도 단김에 빼라.", author: "한국 속담", textEn: "Strike while the iron is hot.", authorEn: "Korean Proverb" },
    { text: "시작이 좋으면 끝도 좋다.", author: "독일 속담", textEn: "A good beginning makes a good ending.", authorEn: "German Proverb" },
    { text: "고생 끝에 낙이 온다.", author: "한국 속담", textEn: "No pain, no gain.", authorEn: "Korean Proverb" },
    { text: "열 번 찍어 안 넘어가는 나무 없다.", author: "한국 속담", textEn: "Little strokes fell great oaks.", authorEn: "Korean Proverb" },
    { text: "작은 고추가 맵다.", author: "한국 속담", textEn: "Good things come in small packages.", authorEn: "Korean Proverb" },
    { text: "아니 땐 굴뚝에 연기 날까.", author: "한국 속담", textEn: "Where there's smoke, there's fire.", authorEn: "Korean Proverb" },
    { text: "낮말은 새가 듣고 밤말은 쥐가 듣는다.", author: "한국 속담", textEn: "Walls have ears.", authorEn: "Korean Proverb" },
    { text: "말이 씨가 된다.", author: "한국 속담", textEn: "Words have power.", authorEn: "Korean Proverb" },
    { text: "호랑이도 제 말 하면 온다.", author: "한국 속담", textEn: "Speak of the devil.", authorEn: "Korean Proverb" },
    { text: "서당 개 삼 년이면 풍월을 읊는다.", author: "한국 속담", textEn: "The sparrow near a school sings the primer.", authorEn: "Korean Proverb" },
    { text: "하늘이 무너져도 솟아날 구멍이 있다.", author: "한국 속담", textEn: "Every cloud has a silver lining.", authorEn: "Korean Proverb" },
    { text: "소 잃고 외양간 고친다.", author: "한국 속담", textEn: "Locking the stable door after the horse has bolted.", authorEn: "Korean Proverb" },
    { text: "우물 안 개구리.", author: "한국 속담", textEn: "A frog in a well.", authorEn: "Korean Proverb" },
    { text: "누워서 떡 먹기.", author: "한국 속담", textEn: "A piece of cake.", authorEn: "Korean Proverb" },
    { text: "그림의 떡.", author: "한국 속담", textEn: "Pie in the sky.", authorEn: "Korean Proverb" },
    { text: "금강산도 식후경.", author: "한국 속담", textEn: "Even the Diamond Mountains are best seen after a meal.", authorEn: "Korean Proverb" },
    { text: "내 코가 석 자.", author: "한국 속담", textEn: "I have my own fish to fry.", authorEn: "Korean Proverb" },
    { text: "남의 떡이 더 커 보인다.", author: "서양 속담", textEn: "The grass is always greener on the other side.", authorEn: "Western Proverb" },
    { text: "친구를 보면 그 사람을 알 수 있다.", author: "미상", textEn: "A man is known by the company he keeps.", authorEn: "Unknown" },
    { text: "책은 마음의 양식이다.", author: "미상", textEn: "Books are food for the mind.", authorEn: "Unknown" },
    { text: "운동은 건강의 근원이다.", author: "미상", textEn: "Exercise is the source of health.", authorEn: "Unknown" },
    { text: "웃음은 최고의 보약이다.", author: "미상", textEn: "Laughter is the best medicine.", authorEn: "Unknown" },
    { text: "사랑은 눈물의 씨앗.", author: "미상", textEn: "Love is the seed of tears.", authorEn: "Unknown" },
    { text: "젊음은 다시 오지 않는다.", author: "미상", textEn: "Youth comes but once.", authorEn: "Unknown" },
    { text: "시간은 돈이다.", author: "벤자민 프랭클린", textEn: "Time is money.", authorEn: "Benjamin Franklin" },
    { text: "습관은 제2의 천성이다.", author: "시세로", textEn: "Habit is a second nature.", authorEn: "Cicero" },
    { text: "고통 없이는 얻는 것도 없다.", author: "벤자민 프랭클린", textEn: "No pain, no gain.", authorEn: "Benjamin Franklin" },
    { text: "연습이 완벽을 만든다.", author: "미상", textEn: "Practice makes perfect.", authorEn: "Unknown" },
    { text: "우리의 인생을 만드는 것은 우리의 생각이다.", author: "마르쿠스 아우렐리우스", textEn: "Our life is what our thoughts make it.", authorEn: "Marcus Aurelius" },
    { text: "행복은 성취의 기쁨과 창조적 노력의 전율에 있다.", author: "프랭클린 D. 루즈벨트", textEn: "Happiness lies in the joy of achievement and the thrill of creative effort.", authorEn: "Franklin D. Roosevelt" },
    { text: "당신이 할 수 있다고 믿든, 할 수 없다고 믿든, 믿는 대로 될 것이다.", author: "헨리 포드", textEn: "Whether you think you can, or you think you can't – you're right.", authorEn: "Henry Ford" },
    { text: "나는 실패한 것이 아니다. 단지 작동하지 않는 10,000가지 방법을 발견했을 뿐이다.", author: "토머스 에디슨", textEn: "I have not failed. I've just found 10,000 ways that won't work.", authorEn: "Thomas Edison" },
    { text: "인생은 자신을 찾는 것이 아니라, 자신을 창조하는 것이다.", author: "조지 버나드 쇼", textEn: "Life is not about finding yourself. Life is about creating yourself.", authorEn: "George Bernard Shaw" },
    { text: "성공은 열정을 잃지 않고 실패를 거듭하는 능력이다.", author: "윈스턴 처칠", textEn: "Success is walking from failure to failure with no loss of enthusiasm.", authorEn: "Winston Churchill" },
    { text: "가장 어두운 밤도 언젠가는 끝나고 해는 떠오른다.", author: "빅토르 위고", textEn: "Even the darkest night will end and the sun will rise.", authorEn: "Victor Hugo" },
    { text: "나 자신을 정복하는 것이야말로 가장 위대한 승리다.", author: "플라톤", textEn: "The first and greatest victory is to conquer yourself.", authorEn: "Plato" },
    { text: "행동 없는 지식은 쓸모가 없다.", author: "공자", textEn: "Knowledge without action is useless.", authorEn: "Confucius" },
    { text: "모든 국가는 그에 걸맞은 정부를 가진다.", author: "조제프 드 메스트르", textEn: "Every nation gets the government it deserves.", authorEn: "Joseph de Maistre" },
    { text: "자유는 책임이다. 그래서 대부분의 사람들은 자유를 두려워한다.", author: "조지 버나드 쇼", textEn: "Liberty means responsibility. That is why most men dread it.", authorEn: "George Bernard Shaw" },
    { text: "진정한 지식은 경험에서 나온다.", author: "알베르트 아인슈타인", textEn: "The only source of knowledge is experience.", authorEn: "Albert Einstein" },
    { text: "인생은 줌인(zoom-in)하면 비극이고, 줌아웃(zoom-out)하면 희극이다.", author: "찰리 채플린", textEn: "Life is a tragedy when seen in close-up, but a comedy in long-shot.", authorEn: "Charlie Chaplin" },
    { text: "내일 죽을 것처럼 살고, 영원히 살 것처럼 배워라.", author: "마하트마 간디", textEn: "Live as if you were to die tomorrow. Learn as if you were to live forever.", authorEn: "Mahatma Gandhi" },
    { text: "약한 자는 절대 용서할 수 없다. 용서는 강한 자의 속성이다.", author: "마하트마 간디", textEn: "The weak can never forgive. Forgiveness is the attribute of the strong.", authorEn: "Mahatma Gandhi" },
    { text: "세상을 바꾸고 싶다면 먼저 자신을 바꿔라.", author: "마하트마 간디", textEn: "You must be the change you wish to see in the world.", authorEn: "Mahatma Gandhi" },
    { text: "눈에는 눈으로만 대하면 온 세상이 장님이 될 것이다.", author: "마하트마 간디", textEn: "An eye for an eye only ends up making the whole world blind.", authorEn: "Mahatma Gandhi" },
    { text: "미래는 현재 우리가 무엇을 하는가에 달려 있다.", author: "마하트마 간디", textEn: "The future depends on what we do in the present.", authorEn: "Mahatma Gandhi" },
    { text: "행복은 당신이 생각하는 것, 말하는 것, 행동하는 것이 조화를 이룰 때 찾아온다.", author: "마하트마 간디", textEn: "Happiness is when what you think, what you say, and what you do are in harmony.", authorEn: "Mahatma Gandhi" },
    { text: "나를 죽이지 못하는 고통은 나를 더 강하게 만든다.", author: "프리드리히 니체", textEn: "That which does not kill us makes us stronger.", authorEn: "Friedrich Nietzsche" },
    { text: "괴물과 싸우는 사람은 그 과정에서 자신마저 괴물이 되지 않도록 조심해야 한다.", author: "프리드리히 니체", textEn: "He who fights with monsters should look to it that he himself does not become a monster.", authorEn: "Friedrich Nietzsche" },
    { text: "신은 죽었다.", author: "프리드리히 니체", textEn: "God is dead.", authorEn: "Friedrich Nietzsche" },
    { text: "음악이 없다면 인생은 실수일 것이다.", author: "프리드리히 니체", textEn: "Without music, life would be a mistake.", authorEn: "Friedrich Nietzsche" },
    { text: "우리가 올라가는 높이만큼, 날지 못하는 사람들에게 우리는 작게 보인다.", author: "프리드리히 니체", textEn: "The higher we soar the smaller we appear to those who cannot fly.", authorEn: "Friedrich Nietzsche" },
    { text: "춤추는 별을 잉태하려면 반드시 스스로의 내면에 혼돈을 지녀야 한다.", author: "프리드리히 니체", textEn: "You must have chaos within you to give birth to a dancing star.", authorEn: "Friedrich Nietzsche" },
    { text: "피할 수 없으면 즐겨라.", author: "로버트 엘리엇", textEn: "If you can't avoid it, enjoy it.", authorEn: "Robert Eliot" },
    { text: "단순하게 살아라. 현대인은 쓸데없는 절차와 일 때문에 얼마나 복잡한 삶을 살아가는가?", author: "이드리스 샤흐", textEn: "Live simply. How complicated life becomes for modern people due to useless procedures and tasks?", authorEn: "Idries Shah" },
    { text: "먼저 자신을 비웃어라. 다른 사람이 당신을 비웃기 전에.", author: "엘사 맥스웰", textEn: "Laugh at yourself first, before anyone else can.", authorEn: "Elsa Maxwell" },
    { text: "먼저 핀 꽃은 먼저 진다. 남보다 먼저 공을 세우려고 조급히 서둘지 마라.", author: "채근담", textEn: "Flowers that bloom early fade early. Do not rush to achieve merit before others.", authorEn: "Caigentan" },
    { text: "행복한 삶을 살기 위해 필요한 것은 거의 없다.", author: "마르쿠스 아우렐리우스", textEn: "Very little is needed to make a happy life.", authorEn: "Marcus Aurelius" },
    { text: "절대 포기하지 마라. 당신이 되고 싶은 무언가가 있다면, 그에 대해 자부심을 가져라.", author: "엠마 톰슨", textEn: "Never give up. If there's something you want to be, take pride in it.", authorEn: "Emma Thompson" },
    { text: "오랫동안 꿈을 그리는 사람은 마침내 그 꿈을 닮아 간다.", author: "앙드레 말로", textEn: "He who dreams for a long time eventually resembles his dream.", authorEn: "Andre Malraux" },
    { text: "좋은 성과를 얻으려면 한 걸음 한 걸음이 힘차고 충실하지 않으면 안 된다.", author: "단테", textEn: "To achieve great results, each step must be strong and faithful.", authorEn: "Dante" },
    { text: "행복은 습관이다, 그것을 몸에 지니라.", author: "허버드", textEn: "Happiness is a habit—cultivate it.", authorEn: "Hubbard" },
    { text: "자신감 있는 표정을 지으면 자신감이 생긴다.", author: "찰스 다윈", textEn: "Wearing a confident expression creates confidence.", authorEn: "Charles Darwin" },
    { text: "평생 살 것처럼 꿈을 꾸고, 내일 죽을 것처럼 오늘을 살아라.", author: "제임스 딘", textEn: "Dream as if you'll live forever. Live as if you'll die today.", authorEn: "James Dean" },
    { text: "성공의 비결은 단 한 가지, 잘할 수 있는 일에 광적으로 집중하는 것이다.", author: "톰 모나건", textEn: "The secret of success is to concentrate fanatically on the one thing you can do well.", authorEn: "Tom Monaghan" },
    { text: "겨울이 오면 봄이 멀지 않으리.", author: "셸리", textEn: "If Winter comes, can Spring be far behind?", authorEn: "Shelley" },
    { text: "인생이란 학교에는 불행이라는 훌륭한 스승이 있다.", author: "프리체", textEn: "In the school of life, there is an excellent teacher called misfortune.", authorEn: "Fritche" },
    { text: "알면서 행하지 않는 것은 모르는 것과 다름없다.", author: "왕양명", textEn: "To know and not to act is the same as not knowing.", authorEn: "Wang Yangming" },
    { text: "사람은 오로지 가슴으로만 올바르게 볼 수 있다. 본질적인 것은 눈에 보이지 않는다.", author: "생텍쥐페리", textEn: "It is only with the heart that one can see rightly; what is essential is invisible to the eye.", authorEn: "Saint-Exupery" },
    { text: "모든 위대한 진리는 처음에는 신성모독으로 시작된다.", author: "조지 버나드 쇼", textEn: "All great truths begin as blasphemies.", authorEn: "George Bernard Shaw" },
    { text: "나는 내 운명의 주인이요, 내 영혼의 선장이다.", author: "윌리엄 헨리", textEn: "I am the master of my fate, I am the captain of my soul.", authorEn: "William Ernest Henley" },
    { text: "변화는 필연적이다. 성장은 선택이다.", author: "존 맥스웰", textEn: "Change is inevitable. Growth is optional.", authorEn: "John Maxwell" },
    { text: "시작이 반이다.", author: "아리스토텔레스", textEn: "Well begun is half done.", authorEn: "Aristotle" },
    { text: "지혜는 경험의 딸이다.", author: "레오나르도 다빈치", textEn: "Wisdom is the daughter of experience.", authorEn: "Leonardo da Vinci" },
    { text: "진실은 결코 속이지 않는다.", author: "칸트", textEn: "Truth never deceives.", authorEn: "Immanuel Kant" },
    { text: "말은 마음의 초상이다.", author: "존 레이", textEn: "Speech is the picture of the mind.", authorEn: "John Ray" },
    { text: "예술은 거짓을 통해 진실을 말한다.", author: "파블로 피카소", textEn: "Art is a lie that makes us realize truth.", authorEn: "Pablo Picasso" },
    { text: "자유는 책임이다. 그래서 대부분의 사람들은 자유를 두려워한다.", author: "조지 버나드 쇼", textEn: "Liberty means responsibility. That is why most men dread it.", authorEn: "George Bernard Shaw" },
    { text: "꿈을 이루기에 너무 늦은 나이란 없다.", author: "조지 엘리엇", textEn: "It is never too late to be what you might have been.", authorEn: "George Eliot" },
    { text: "삶이 있는 한 희망은 있다.", author: "키케로", textEn: "While there's life, there's hope.", authorEn: "Cicero" },
    { text: "산다는 것은 숨 쉬는 것이 아니라 행동하는 것이다.", author: "루소", textEn: "To live is not to breathe but to act.", authorEn: "Jean-Jacques Rousseau" },
    { text: "언제나 현재에 집중할 수 있다면 행복할 것이다.", author: "파울로 코엘료", textEn: "If you can always concentrate on the present, you'll be a happy man.", authorEn: "Paulo Coelho" },
    { text: "신은 용기 있는 자를 결코 버리지 않는다.", author: "켄러", textEn: "God never abandons the courageous.", authorEn: "Kenner" },
    { text: "피할 수 없으면 즐겨라.", author: "로버트 엘리엇", textEn: "If you can't avoid it, enjoy it.", authorEn: "Robert Eliot" },
    { text: "단순하게 살아라.", author: "이드리스 샤흐", textEn: "Live simply.", authorEn: "Idries Shah" },
    { text: "사랑은 모든 것을 이긴다.", author: "버질", textEn: "Love conquers all.", authorEn: "Virgil" },
    { text: "용서는 복수보다 낫다.", author: "피타쿠스", textEn: "Forgiveness is better than revenge.", authorEn: "Pittacus" },
    { text: "인내는 쓰지만 그 열매는 달다.", author: "루소", textEn: "Patience is bitter, but its fruit is sweet.", authorEn: "Jean-Jacques Rousseau" },
    { text: "시간이 약이다.", author: "서양 속담", textEn: "Time heals all wounds.", authorEn: "Western Proverb" },
    { text: "아는 것이 힘이다.", author: "프랜시스 베이컨", textEn: "Knowledge is power.", authorEn: "Francis Bacon" },
    { text: "약속은 빚이다.", author: "독일 속담", textEn: "A promise is a debt.", authorEn: "German Proverb" },
    { text: "침묵은 금이다.", author: "토마스 칼라일", textEn: "Silence is golden.", authorEn: "Thomas Carlyle" },
    { text: "펜은 칼보다 강하다.", author: "에드워드 불워 리턴", textEn: "The pen is mightier than the sword.", authorEn: "Edward Bulwer-Lytton" },
    { text: "역사는 되풀이된다.", author: "투키디데스", textEn: "History repeats itself.", authorEn: "Thucydides" },
    { text: "모든 길은 로마로 통한다.", author: "라 퐁텐", textEn: "All roads lead to Rome.", authorEn: "La Fontaine" },
    { text: "로마는 하루아침에 이루어지지 않았다.", author: "세르반테스", textEn: "Rome was not built in a day.", authorEn: "Cervantes" },
    { text: "시작이 좋으면 끝도 좋다.", author: "독일 속담", textEn: "A good beginning makes a good ending.", authorEn: "German Proverb" },
    { text: "책은 마음의 양식이다.", author: "미상", textEn: "Books are food for the mind.", authorEn: "Unknown" },
    { text: "웃음은 최고의 보약이다.", author: "미상", textEn: "Laughter is the best medicine.", authorEn: "Unknown" },
    { text: "시간은 돈이다.", author: "벤자민 프랭클린", textEn: "Time is money.", authorEn: "Benjamin Franklin" },
    { text: "습관은 제2의 천성이다.", author: "시세로", textEn: "Habit is a second nature.", authorEn: "Cicero" },
    { text: "고통 없이는 얻는 것도 없다.", author: "벤자민 프랭클린", textEn: "No pain, no gain.", authorEn: "Benjamin Franklin" },
    { text: "연습이 완벽을 만든다.", author: "미상", textEn: "Practice makes perfect.", authorEn: "Unknown" },
    { text: "백문이 불여일견.", author: "반고", textEn: "Seeing is believing.", authorEn: "Ban Gu" },
    { text: "천재는 1%의 영감과 99%의 땀으로 이루어진다.", author: "에디슨", textEn: "Genius is one percent inspiration and ninety-nine percent perspiration.", authorEn: "Thomas Edison" },
    { text: "가장 큰 위험은 위험 없는 삶이다.", author: "스티븐 코비", textEn: "The greatest risk is the risk of riskless living.", authorEn: "Stephen Covey" },
    { text: "모든 성취의 시작점은 갈망이다.", author: "나폴레온 힐", textEn: "The starting point of all achievement is desire.", authorEn: "Napoleon Hill" },
    { text: "독서가 정신에 미치는 영향은 운동이 신체에 미치는 영향과 같다.", author: "리처드 스틸", textEn: "Reading is to the mind what exercise is to the body.", authorEn: "Richard Steele" },
    { text: "상상력은 지식보다 중요하다.", author: "알베르트 아인슈타인", textEn: "Imagination is more important than knowledge.", authorEn: "Albert Einstein" },
    { text: "논리는 당신을 A에서 B로 이끌지만, 상상력은 당신을 어디든 데려갈 것이다.", author: "알베르트 아인슈타인", textEn: "Logic will get you from A to B. Imagination will take you everywhere.", authorEn: "Albert Einstein" },
    { text: "어제에서 배우고, 오늘을 살며, 내일을 희망하라.", author: "알베르트 아인슈타인", textEn: "Learn from yesterday, live for today, hope for tomorrow.", authorEn: "Albert Einstein" },
    { text: "실수를 해보지 않은 사람은 결코 새로운 시도를 하지 않은 사람이다.", author: "알베르트 아인슈타인", textEn: "Anyone who has never made a mistake has never tried anything new.", authorEn: "Albert Einstein" },
    { text: "편견은 이성이 있기 전의 의견이다.", author: "볼테르", textEn: "Prejudice is opinion without judgment.", authorEn: "Voltaire" },
    { text: "나는 당신의 말에 동의하지 않지만, 당신이 그 말을 할 권리는 죽을 때까지 옹호할 것이다.", author: "볼테르", textEn: "I disapprove of what you say, but I will defend to the death your right to say it.", authorEn: "Voltaire" },
    { text: "행복은 성취의 기쁨과 창조적 노력의 전율 속에 있다.", author: "프랭클린 D. 루즈벨트", textEn: "Happiness lies in the joy of achievement and the thrill of creative effort.", authorEn: "Franklin D. Roosevelt" },
    { text: "어둠 속에서도 별은 빛난다.", author: "에머슨", textEn: "Stars shine even in the darkness.", authorEn: "Ralph Waldo Emerson" },
    { text: "인생은 속도가 아니라 방향이다.", author: "괴테", textEn: "Life is not about speed, but direction.", authorEn: "Goethe" },
    { text: "가장 큰 모험은 당신이 꿈꾸는 삶을 사는 것이다.", author: "오프라 윈프리", textEn: "The biggest adventure you can take is to live the life of your dreams.", authorEn: "Oprah Winfrey" },
    { text: "실패는 다시 시작할 수 있는 기회일 뿐이다. 이번에는 더 현명하게.", author: "헨리 포드", textEn: "Failure is simply the opportunity to begin again, this time more intelligently.", authorEn: "Henry Ford" },
    { text: "당신이 동의하지 않는 한, 아무도 당신에게 열등감을 느끼게 할 수 없다.", author: "엘리너 루즈벨트", textEn: "No one can make you feel inferior without your consent.", authorEn: "Eleanor Roosevelt" },
    { text: "우리가 두려워해야 할 유일한 것은 두려움 그 자체다.", author: "프랭클린 D. 루즈벨트", textEn: "The only thing we have to fear is fear itself.", authorEn: "Franklin D. Roosevelt" },
    { text: "성공은 최종적인 것이 아니며, 실패는 치명적인 것이 아니다. 중요한 것은 계속하는 용기다.", author: "윈스턴 처칠", textEn: "Success is not final, failure is not fatal: it is the courage to continue that counts.", authorEn: "Winston Churchill" },
    { text: "당신의 시간은 제한되어 있다. 그러니 다른 사람의 삶을 사느라 낭비하지 마라.", author: "스티브 잡스", textEn: "Your time is limited, so don't waste it living someone else's life.", authorEn: "Steve Jobs" },
    { text: "위대한 일을 하는 유일한 방법은 당신이 하는 일을 사랑하는 것이다.", author: "스티브 잡스", textEn: "The only way to do great work is to love what you do.", authorEn: "Steve Jobs" },
    { text: "혁신은 리더와 추종자를 구분하는 잣대다.", author: "스티브 잡스", textEn: "Innovation distinguishes between a leader and a follower.", authorEn: "Steve Jobs" },
    { text: "인생은 10%의 사건과 90%의 반응으로 이루어진다.", author: "찰스 스윈돌", textEn: "Life is 10% what happens to you and 90% how you react to it.", authorEn: "Charles Swindoll" },
    { text: "가장 좋은 복수는 엄청난 성공이다.", author: "프랭크 시나트라", textEn: "The best revenge is massive success.", authorEn: "Frank Sinatra" },
    { text: "믿음은 보이지 않는 것을 믿는 것이며, 그 보상은 믿는 것을 보는 것이다.", author: "성 아우구스티누스", textEn: "Faith is to believe what you do not see; the reward of this faith is to see what you believe.", authorEn: "Saint Augustine" },
    { text: "사랑은 두 사람이 마주 쳐다보는 것이 아니라, 함께 같은 방향을 바라보는 것이다.", author: "생텍쥐페리", textEn: "Love does not consist in gazing at each other, but in looking outward together in the same direction.", authorEn: "Saint-Exupery" },
    { text: "진정한 여행은 새로운 풍경을 보는 것이 아니라, 새로운 눈을 가지는 것이다.", author: "마르셀 프루스트", textEn: "The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.", authorEn: "Marcel Proust" },
    { text: "사람은 자신이 생각하는 대로 된다.", author: "얼 나이팅게일", textEn: "We become what we think about.", authorEn: "Earl Nightingale" },
    { text: "나무를 심기에 가장 좋은 때는 20년 전이었다. 두 번째로 좋은 때는 지금이다.", author: "중국 속담", textEn: "The best time to plant a tree was 20 years ago. The second best time is now.", authorEn: "Chinese Proverb" },
    { text: "천 리 길도 한 걸음부터.", author: "노자", textEn: "A journey of a thousand miles begins with a single step.", authorEn: "Lao Tzu" },
    { text: "강을 거슬러 헤엄치는 자가 강을 안다.", author: "이탈리아 속담", textEn: "Only he who swims against the stream knows the strength of it.", authorEn: "Italian Proverb" },
    { text: "배움에는 왕도가 없다.", author: "유클리드", textEn: "There is no royal road to learning.", authorEn: "Euclid" },
    { text: "건강은 최고의 자산이다.", author: "버질", textEn: "The greatest wealth is health.", authorEn: "Virgil" },
    { text: "웃음은 두 사람 사이의 가장 가까운 거리다.", author: "빅터 보르게", textEn: "Laughter is the shortest distance between two people.", authorEn: "Victor Borge" },
    { text: "침묵은 때로 말보다 더 웅변적이다.", author: "토마스 칼라일", textEn: "Silence is more eloquent than words.", authorEn: "Thomas Carlyle" },
    { text: "인내심은 희망을 갖는 기술이다.", author: "보븐자르그", textEn: "Patience is the art of hoping.", authorEn: "Vauvenargues" },
    { text: "친절은 결코 헛되지 않는다.", author: "이솝", textEn: "No act of kindness, no matter how small, is ever wasted.", authorEn: "Aesop" },
    { text: "다른 사람을 비난하지 마라. 그 사람이 당신의 신발을 신고 걸어보지 않았다면.", author: "인디언 속담", textEn: "Never criticize a man until you've walked a mile in his moccasins.", authorEn: "Native American Proverb" },
    { text: "모든 것은 마음먹기에 달렸다.", author: "원효대사", textEn: "Everything depends on your mind.", authorEn: "Wonhyo" },
    { text: "말조심은 지혜의 머리다.", author: "한국 속담", textEn: "Discretion in speech is more than eloquence.", authorEn: "Korean Proverb" },
    { text: "시간은 모든 상처를 치유한다.", author: "메난드로스", textEn: "Time heals all wounds.", authorEn: "Menander" },
    { text: "지혜로운 사람은 당황하지 않고, 어진 사람은 근심하지 않으며, 용기 있는 사람은 두려워하지 않는다.", author: "공자", textEn: "The wise are not perplexed, the benevolent are not anxious, and the bold are not afraid.", authorEn: "Confucius" },
    { text: "배우고 때로 익히면 또한 기쁘지 아니한가.", author: "공자", textEn: "To learn and at due times to repeat what one has learnt, is that not after all a pleasure?", authorEn: "Confucius" },
    { text: "세 사람이 걸어가면 반드시 나의 스승이 있다.", author: "공자", textEn: "When I walk along with two others, they may serve me as my teachers.", authorEn: "Confucius" },
    { text: "과거를 지배하는 자가 미래를 지배한다.", author: "조지 오웰", textEn: "Who controls the past controls the future. Who controls the present controls the past.", authorEn: "George Orwell" },
    { text: "자유가 아니면 죽음을 달라.", author: "패트릭 헨리", textEn: "Give me liberty, or give me death!", authorEn: "Patrick Henry" },
    { text: "내 사전에 불가능이란 단어는 없다.", author: "나폴레옹", textEn: "Impossible is a word to be found only in the dictionary of fools.", authorEn: "Napoleon" },
    { text: "소년이여, 야망을 가져라.", author: "윌리엄 클라크", textEn: "Boys, be ambitious!", authorEn: "William Clark" },
    { text: "나는 생각한다, 고로 존재한다.", author: "데카르트", textEn: "I think, therefore I am.", authorEn: "Descartes" },
    { text: "아는 것이 힘이다.", author: "프랜시스 베이컨", textEn: "Knowledge is power.", authorEn: "Francis Bacon" },
    { text: "시간은 금이다.", author: "벤자민 프랭클린", textEn: "Time is money.", authorEn: "Benjamin Franklin" },
    { text: "천재는 1%의 영감과 99%의 땀으로 이루어진다.", author: "에디슨", textEn: "Genius is one percent inspiration and ninety-nine percent perspiration.", authorEn: "Thomas Edison" },
    { text: "성공은 준비와 기회가 만나는 곳에 있다.", author: "보비 언서", textEn: "Success is where preparation and opportunity meet.", authorEn: "Bobby Unser" },
    { text: "행운은 용기를 좋아한다.", author: "로마 속담", textEn: "Fortune favors the bold.", authorEn: "Roman Proverb" },
    { text: "최선을 다하라, 그리고 나머지는 잊어라.", author: "월터 앨스턴", textEn: "Do your best and forget the rest.", authorEn: "Walter Alston" },
    { text: "할 수 있다고 믿는 사람은 그렇게 되고, 할 수 없다고 믿는 사람 역시 그렇게 된다.", author: "샤를 드골", textEn: "He who believes he can and he who believes he can't are both usually right.", authorEn: "Charles de Gaulle" },
    { text: "승리하는 자는 결코 포기하지 않고, 포기하는 자는 결코 승리하지 못한다.", author: "빈스 롬바르디", textEn: "Winners never quit and quitters never win.", authorEn: "Vince Lombardi" },
    { text: "어제를 후회하지 마라. 인생은 오늘 나를 위해 있다.", author: "명언", textEn: "Don't regret yesterday. Life is for me today.", authorEn: "Unknown" },
    { text: "오늘이 당신의 남은 인생의 첫날이다.", author: "아메리칸 뷰티", textEn: "Today is the first day of the rest of your life.", authorEn: "American Beauty" },
    { text: "삶은 풀어야 할 문제가 아니라 경험해야 할 현실이다.", author: "소런 키에르케고르", textEn: "Life is not a problem to be solved, but a reality to be experienced.", authorEn: "Soren Kierkegaard" },
    { text: "우리의 인생은 우리의 생각이 만든다.", author: "마르쿠스 아우렐리우스", textEn: "Our life is what our thoughts make it.", authorEn: "Marcus Aurelius" },
    { text: "행복은 우리 자신에게 달려 있다.", author: "아리스토텔레스", textEn: "Happiness depends upon ourselves.", authorEn: "Aristotle" },
    { text: "자신을 알라.", author: "소크라테스", textEn: "Know thyself.", authorEn: "Socrates" },
    { text: "검토되지 않은 삶은 살 가치가 없다.", author: "소크라테스", textEn: "The unexamined life is not worth living.", authorEn: "Socrates" },
    { text: "유일한 선은 앎이요, 유일한 악은 무지다.", author: "소크라테스", textEn: "There is only one good, knowledge, and one evil, ignorance.", authorEn: "Socrates" },
    { text: "나는 내가 아무것도 모른다는 것을 안다.", author: "소크라테스", textEn: "I know that I know nothing.", authorEn: "Socrates" },
    { text: "정의란 각자에게 자신의 몫을 주는 것이다.", author: "플라톤", textEn: "Justice means giving every man his due.", authorEn: "Plato" },
    { text: "용기는 두려움을 느끼지 않는 것이 아니라 두려움에 대한 저항이자 정복이다.", author: "마크 트웨인", textEn: "Courage is resistance to fear, mastery of fear, not absence of fear.", authorEn: "Mark Twain" },
    { text: "인생은 가까이서 보면 비극이지만 멀리서 보면 희극이다.", author: "찰리 채플린", textEn: "Life is a tragedy when seen in close-up, but a comedy in long-shot.", authorEn: "Charlie Chaplin" },
    { text: "가장 낭비된 날은 웃지 않은 날이다.", author: "이. 이. 커밍스", textEn: "The most wasted of all days is one without laughter.", authorEn: "E. E. Cummings" },
    { text: "우리가 잃어버린 것들에 대해 슬퍼하지 말고, 남은 것들에 대해 감사하자.", author: "명언", textEn: "Do not grieve for what you have lost, but be grateful for what you have left.", authorEn: "Unknown" },
    { text: "세상을 변화시키려는 사람은 먼저 자신부터 변화시켜야 한다.", author: "소크라테스", textEn: "Let him that would move the world first move himself.", authorEn: "Socrates" },
    { text: "사랑은 눈으로 보지 않고 마음으로 본다.", author: "셰익스피어", textEn: "Love looks not with the eyes, but with the mind.", authorEn: "Shakespeare" },
    { text: "약한 자는 절대 용서할 수 없다. 용서는 강한 자의 속성이다.", author: "마하트마 간디", textEn: "The weak can never forgive. Forgiveness is the attribute of the strong.", authorEn: "Mahatma Gandhi" },
    { text: "눈에는 눈으로만 대하면 온 세상이 장님이 될 것이다.", author: "마하트마 간디", textEn: "An eye for an eye only ends up making the whole world blind.", authorEn: "Mahatma Gandhi" },
    { text: "내일 죽을 것처럼 살고, 영원히 살 것처럼 배워라.", author: "마하트마 간디", textEn: "Live as if you were to die tomorrow. Learn as if you were to live forever.", authorEn: "Mahatma Gandhi" },
    { text: "행복은 당신이 생각하는 것, 말하는 것, 행동하는 것이 조화를 이룰 때 찾아온다.", author: "마하트마 간디", textEn: "Happiness is when what you think, what you say, and what you do are in harmony.", authorEn: "Mahatma Gandhi" },
    { text: "변화는 우리가 누군가를 기다리거나 다른 때를 기다린다고 오지 않는다. 우리 자신이 우리가 기다리던 사람들이다.", author: "버락 오바마", textEn: "Change will not come if we wait for some other person or some other time. We are the ones we've been waiting for.", authorEn: "Barack Obama" },
    { text: "우리가 할 수 있는 가장 위대한 모험은 꿈꾸던 삶을 사는 것이다.", author: "오프라 윈프리", textEn: "The biggest adventure you can take is to live the life of your dreams.", authorEn: "Oprah Winfrey" },
    { text: "당신이 할 수 있는 가장 큰 실수는 실수를 할까 봐 끊임없이 두려워하는 것이다.", author: "엘버트 허바드", textEn: "The greatest mistake you can make in life is to be continually fearing you will make one.", authorEn: "Elbert Hubbard" },
    { text: "성공은 열정을 잃지 않고 실패를 거듭하는 능력이다.", author: "윈스턴 처칠", textEn: "Success is walking from failure to failure with no loss of enthusiasm.", authorEn: "Winston Churchill" },
    { text: "비관론자는 모든 기회에서 어려움을 보고, 낙관론자는 모든 어려움에서 기회를 본다.", author: "윈스턴 처칠", textEn: "A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty.", authorEn: "Winston Churchill" },
    { text: "절대로, 절대로, 절대로 포기하지 마라.", author: "윈스턴 처칠", textEn: "Never, never, never give up.", authorEn: "Winston Churchill" },
    { text: "당신이 지옥을 통과하고 있다면, 멈추지 말고 계속 가라.", author: "윈스턴 처칠", textEn: "If you are going through hell, keep going.", authorEn: "Winston Churchill" },
    { text: "삶의 가장 큰 영광은 결코 넘어지지 않는 데 있는 것이 아니라 넘어질 때마다 일어서는 데 있다.", author: "넬슨 만델라", textEn: "The greatest glory in living lies not in never falling, but in rising every time we fall.", authorEn: "Nelson Mandela" },
    { text: "어려워 보일지라도, 끝까지 해내면 그것은 항상 불가능해 보인다.", author: "넬슨 만델라", textEn: "It always seems impossible until it's done.", authorEn: "Nelson Mandela" },
    { text: "나는 나의 영혼의 선장이다.", author: "윌리엄 헨리", textEn: "I am the captain of my soul.", authorEn: "William Ernest Henley" },
    { text: "나를 정의하는 것은 내가 겪은 일이 아니라 내가 선택한 것이다.", author: "칼 융", textEn: "I am not what happened to me, I am what I choose to become.", authorEn: "Carl Jung" },
    { text: "다른 사람을 정복하는 자는 강한 자이지만, 자신을 정복하는 자는 위대한 자이다.", author: "노자", textEn: "He who conquers others is strong; He who conquers himself is mighty.", authorEn: "Lao Tzu" },
    { text: "천 리 길도 발밑에서 시작한다.", author: "노자", textEn: "A journey of a thousand miles begins beneath one's feet.", authorEn: "Lao Tzu" },
    { text: "가장 부드러운 것이 가장 강한 것을 이긴다.", author: "노자", textEn: "The softest things in the world overcome the hardest things in the world.", authorEn: "Lao Tzu" },
    { text: "만족할 줄 아는 사람은 영원히 부유하다.", author: "노자", textEn: "He who is contented is rich.", authorEn: "Lao Tzu" },
    { text: "지혜로운 자는 물과 같다.", author: "노자", textEn: "The highest good is like water.", authorEn: "Lao Tzu" },
    { text: "자연은 서두르지 않지만 모든 것을 이룬다.", author: "노자", textEn: "Nature does not hurry, yet everything is accomplished.", authorEn: "Lao Tzu" },
    { text: "인생은 짧고 예술은 길다.", author: "히포크라테스", textEn: "Life is short, art is long.", authorEn: "Hippocrates" },
    { text: "건강은 가장 큰 선물, 만족은 가장 큰 재산, 신뢰는 가장 큰 친척이다.", author: "부처", textEn: "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", authorEn: "Buddha" },
    { text: "마음은 모든 것이다. 당신은 당신이 생각하는 대로 된다.", author: "부처", textEn: "The mind is everything. What you think you become.", authorEn: "Buddha" },
    { text: "과거에 연연하지 말고, 미래를 꿈꾸지 말고, 현재의 순간에 집중하라.", author: "부처", textEn: "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", authorEn: "Buddha" },
    { text: "평화는 내면에서 온다. 밖에서 찾지 마라.", author: "부처", textEn: "Peace comes from within. Do not seek it without.", authorEn: "Buddha" },
    { text: "분노를 품는 것은 독을 마시고 다른 사람이 죽기를 바라는 것과 같다.", author: "부처", textEn: "Holding on to anger is like drinking poison and expecting the other person to die.", authorEn: "Buddha" },
    { text: "고통은 필연적이지만, 괴로움은 선택이다.", author: "무라카미 하루키", textEn: "Pain is inevitable. Suffering is optional.", authorEn: "Haruki Murakami" },
    { text: "작은 일에 충실하라. 당신을 위대하게 만드는 것은 바로 그 작은 일들이다.", author: "마더 테레사", textEn: "Be faithful in small things because it is in them that your strength lies.", authorEn: "Mother Teresa" },
    { text: "사랑은 사계절 내내 열리는 열매와 같다.", author: "마더 테레사", textEn: "Love is a fruit in season at all times, and within reach of every hand.", authorEn: "Mother Teresa" },
    { text: "평화를 원한다면 집에 가서 가족을 사랑하라.", author: "마더 테레사", textEn: "If you want peace, go home and love your family.", authorEn: "Mother Teresa" },
    { text: "나는 친절이 세상을 구할 수 있다고 믿는다.", author: "알베르 카뮈", textEn: "I believe that kindness can save the world.", authorEn: "Albert Camus" },
    { text: "겨울 한복판에서 나는 내 안에 굴복하지 않는 여름이 있다는 것을 알았다.", author: "알베르 카뮈", textEn: "In the midst of winter, I found there was, within me, an invincible summer.", authorEn: "Albert Camus" },
    { text: "행복해지기 위해 모든 것이 완벽할 필요는 없다.", author: "알버트 슈바이처", textEn: "You don't need everything to be perfect to be happy.", authorEn: "Albert Schweitzer" },
];

export function getDailyQuote(): Quote {
    // 현재 날짜를 기준으로 인덱스 생성 (KST 기준)
    // 1. 현재 시간(UTC)을 가져옴
    const now = new Date();
    // 2. KST(UTC+9)로 변환: 9시간 * 60분 * 60초 * 1000밀리초 더함
    const kstOffset = 9 * 60 * 60 * 1000;
    const kstDate = new Date(now.getTime() + kstOffset);

    // 3. YYYY-MM-DD 형식으로 변환
    const today = kstDate.toISOString().slice(0, 10);

    // 간단한 해시 함수: 날짜 문자열의 각 문자의 코드값을 더함
    let hash = 0;
    for (let i = 0; i < today.length; i++) {
        hash = today.charCodeAt(i) + ((hash << 5) - hash);
    }

    // 음수 처리 및 배열 길이로 모듈러 연산
    const index = Math.abs(hash) % quotes.length;

    return quotes[index];
}

function getKSTDate(date?: Date): Date {
    const target = date || new Date();
    // 1. 현재 시간(UTC)을 가져옴 -> target is already in UTC context if standard Date
    // 2. KST(UTC+9)로 변환
    const kstOffset = 9 * 60 * 60 * 1000;
    return new Date(target.getTime() + kstOffset);
}

export function getQuoteForDate(dateString: string): Quote {
    let hash = 0;
    for (let i = 0; i < dateString.length; i++) {
        hash = dateString.charCodeAt(i) + ((hash << 5) - hash);
    }
    const index = Math.abs(hash) % quotes.length;
    return quotes[index];
}

export function getPastQuotes(days: number): { date: string; quote: Quote }[] {
    const history = [];
    const now = new Date();

    for (let i = 0; i < days; i++) {
        const pastDate = new Date(now);
        pastDate.setDate(now.getDate() - i);

        const kstDate = getKSTDate(pastDate);
        const dateString = kstDate.toISOString().slice(0, 10);

        history.push({
            date: dateString,
            quote: getQuoteForDate(dateString)
        });
    }
    return history;
}
